import { genres } from "./mockMovies";

const person = {
  adult: false,
  also_known_as: [
    "Леонардо ДиКаприо",
    "ليوناردو دي كابريو",
    "레오나르도 디카프리오",
    "レオナルド・ディカプリオ",
    "ลีโอนาร์โด ดิแคพรีโอ",
    "莱昂纳多·迪卡普里奥",
    "Leo DiCaprio",
    "Leonardo Wilhelm DiCaprio",
    "Λεονάρντο Ντι Κάπριο",
    "Ντι Κάπριο",
    "Леонардо Ді Капріо",
    "Леонардо ДіКапріо",
    "לאונרדו דיקפריו",
    "ലിയനാർഡോ ഡികാപ്രിയോ",
    "Leonardo Di Caprio",
  ],
  biography:
    "Leonardo DiCaprio (born November 11, 1974) is an American actor, film producer, and environmental activist.\n\nHe began his film career by starring as Josh in Critters 3 before starring in the film adaptation of the memoir This Boy's Life (1993) alongside Robert De Niro. DiCaprio was praised for his supporting role in the drama What's Eating Gilbert Grape (1993), and gained public recognition with leading roles in the drama The Basketball Diaries (1995) and the romantic drama Romeo + Juliet (1996), before achieving international fame with James Cameron's epic romance Titanic (1997) He has been nominated for six Academy Awards—five for acting and one for producing—and in 2016, he won the Academy Award for Best Actor for The Revenant.\n\nDiCaprio is the founder of his own production company, named Appian Way Productions. He is also a committed environmentalist.",
  birthday: "1974-11-11",
  deathday: null,
  gender: 2,
  homepage: "http://leonardodicaprio.com",
  id: 6193,
  imdb_id: "nm0000138",
  known_for_department: "Acting",
  name: "Leonardo DiCaprio",
  place_of_birth: "Los Angeles, California, USA",
  popularity: 26.158,
  profile_path: "/posters/titanic/Leo.jpeg",
};

let movies = {
  cast: [
    {
      voteAverage: 6.8,
      id: 454,
      overview:
        "In director Baz Luhrmann's contemporary take on William Shakespeare's classic tragedy, the Montagues and Capulets have moved their ongoing feud to the sweltering suburb of Verona Beach, where Romeo and Juliet fall in love and secretly wed. Though the film is visually modern, the bard's dialogue remains.",
      release_date: "1996-11-01",
      adult: false,
      backdrop_path: "/pGj2x2lInWeHsWuBMgpqfDB1x9T.jpg",
      genreIds: [18, 10749],
      vote_count: 4031,
      original_language: "en",
      originalTitle: "Romeo + Juliet",
      posterPath: "/zWLZEUE0jrTiLhWQVh8NOJRwIU9.jpg",
      title: "Romeo + Juliet",
      video: false,
      popularity: 21.388,
      character: "Romeo",
      credit_id: "52fe4245c3a36847f80114bf",
      order: 0,
    },
    {
      overview:
        "101-year-old Rose DeWitt Bukater tells the story of her life aboard the Titanic, 84 years later. A young Rose boards the ship with her mother and fiancé. Meanwhile, Jack Dawson and Fabrizio De Rossi win third-class tickets aboard the ship. Rose tells the whole story from Titanic's departure through to its death—on its first and last voyage—on April 15, 1912.",
      release_date: "1997-11-18",
      adult: false,
      backdrop_path: "/6VmFqApQRyZZzmiGOQq2C92jyvH.jpg",
      genreIds: [18, 10749],
      vote_count: 19937,
      original_language: "en",
      originalTitle: "Titanic",
      id: 597,
      title: "Titanic",
      video: false,
      voteAverage: 7.9,
      posterPath: "/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg",
      popularity: 105.231,
      character: "Jack Dawson",
      credit_id: "52fe425ac3a36847f80179cf",
      order: 0,
    },
    {
      adult: false,
      id: 1372,
      voteAverage: 7.5,
      genreIds: [18, 53, 28],
      vote_count: 5881,
      original_language: "en",
      originalTitle: "Blood Diamond",
      posterPath: "/m6rZ3dmqjcTvVNKtqwQ6hxYQ9nk.jpg",
      video: false,
      title: "Blood Diamond",
      backdrop_path: "/obKCYv66xyqEi0aswy0A9IWHa5f.jpg",
      overview:
        "An ex-mercenary turned smuggler. A Mende fisherman. Amid the explosive civil war overtaking 1999 Sierra Leone, these men join for two desperate missions: recovering a rare pink diamond of immense value and rescuing the fisherman's son, conscripted as a child soldier into the brutal rebel forces ripping a swath of torture and bloodshed countrywide.",
      release_date: "2006-01-26",
      popularity: 27.543,
      character: "Danny Archer",
      credit_id: "52fe42f0c3a36847f802e687",
      order: 0,
    },
    {
      backdrop_path: "/cxRcmEwtUZVfNlC4HoWaNKzNNW0.jpg",
      genreIds: [18, 12, 10749, 53],
      original_language: "en",
      originalTitle: "The Beach",
      posterPath: "/Ai1iDX065HBFhtcbxJVwhzJniv0.jpg",
      id: 1907,
      video: false,
      voteAverage: 6.4,
      overview:
        "Twenty-something Richard travels to Thailand and finds himself in possession of a strange map. Rumours state that it leads to a solitary beach paradise, a tropical bliss - excited and intrigued, he sets out to find it.",
      release_date: "2000-02-03",
      vote_count: 3424,
      title: "The Beach",
      adult: false,
      popularity: 14.696,
      character: "Richard",
      credit_id: "52fe4320c3a36847f803c4fb",
      order: 0,
    },
    {
      genreIds: [18],
      original_language: "en",
      originalTitle: "The Aviator",
      posterPath: "/lx4kWcZc3o9PaNxlQpEJZM17XUI.jpg",
      video: false,
      voteAverage: 7.2,
      vote_count: 4108,
      overview:
        "A biopic depicting the life of filmmaker and aviation pioneer Howard Hughes from 1927 to 1947, during which time he became a successful film producer and an aviation magnate, while simultaneously growing more unstable due to severe obsessive-compulsive disorder.",
      id: 2567,
      release_date: "2004-12-17",
      title: "The Aviator",
      adult: false,
      backdrop_path: "/dFs5aShkZWiaeM7bHbn2tK5o8Zh.jpg",
      popularity: 19.573,
      character: "Howard Hughes",
      credit_id: "52fe435dc3a36847f804ed4b",
      order: 0,
    },
    {
      adult: false,
      id: 10474,
      voteAverage: 7.4,
      genreIds: [18, 80],
      vote_count: 1408,
      original_language: "en",
      originalTitle: "The Basketball Diaries",
      posterPath: "/AhvO1GGDPIgN0hOqZEgaFCbswMK.jpg",
      video: false,
      title: "The Basketball Diaries",
      backdrop_path: "/nb8pMW3o85jATvhz7y6clAFlL1u.jpg",
      overview:
        "A high school basketball player’s life turns upside down after free-falling into the harrowing world of drug addiction.",
      release_date: "1995-04-21",
      popularity: 22.046,
      character: "Jim Carroll",
      credit_id: "52fe43779251416c750116ab",
      order: 0,
    },
    {
      originalTitle: "Gangs of New York",
      posterPath: "/lemqKtcCuAano5aqrzxYiKC8kkn.jpg",
      video: false,
      voteAverage: 7.3,
      overview:
        "It's 1863. America was born in the streets. Amsterdam Vallon returns to the Five Points of America to seek vengeance against the psychotic gangland kingpin, Bill the Butcher, who murdered his father years earlier. With an eager pickpocket by his side and a whole new army, Vallon fights his way to seek vengeance on the Butcher and restore peace in the area.",
      id: 3131,
      vote_count: 5163,
      adult: false,
      backdrop_path: "/a2Aj5ksEo2HOUH3FbGyZCtaJM4C.jpg",
      title: "Gangs of New York",
      genreIds: [18, 36, 80],
      release_date: "2002-12-14",
      original_language: "en",
      popularity: 19.059,
      character: "Amsterdam Vallon",
      credit_id: "52fe4389c3a36847f805bbc1",
      order: 0,
    },
    {
      overview:
        "A young couple living in a Connecticut suburb during the mid-1950s struggle to come to terms with their personal problems while trying to raise their two children. Based on a novel by Richard Yates.",
      release_date: "2008-12-19",
      adult: false,
      backdrop_path: "/8LJgY2DOv7rWMvbPKHVqHr3PM2X.jpg",
      vote_count: 3001,
      genreIds: [18, 10749],
      voteAverage: 6.9,
      original_language: "en",
      originalTitle: "Revolutionary Road",
      posterPath: "/1jYKJEGcgbkEjlKuY94Dv7BVe1P.jpg",
      title: "Revolutionary Road",
      video: false,
      id: 4148,
      popularity: 17.178,
      character: "Frank Wheeler",
      credit_id: "52fe43afc3a36847f8067929",
      order: 0,
    },
    {
      genreIds: [18, 53, 9648],
      title: "Shutter Island",
      original_language: "en",
      originalTitle: "Shutter Island",
      posterPath: "/52d7CAjnwh1cZXd2lhKaHVFMu0Q.jpg",
      video: false,
      voteAverage: 8.2,
      id: 11324,
      release_date: "2010-02-14",
      vote_count: 18704,
      adult: false,
      backdrop_path: "/U8QRD7jvTXEYsUXq74IFKaSiL5.jpg",
      overview:
        "World War II soldier-turned-U.S. Marshal Teddy Daniels investigates the disappearance of a patient from a hospital for the criminally insane, but his efforts are compromised by his troubling visions and also by a mysterious doctor.",
      popularity: 48.79,
      character: "Teddy Daniels",
      credit_id: "52fe44269251416c7502a8ab",
      order: 0,
    },
    {
      adult: false,
      backdrop_path: "/iViUI5bTnYkgQ9ty1CXQ8J4obby.jpg",
      genreIds: [28, 18, 53],
      id: 12113,
      original_language: "en",
      originalTitle: "Body of Lies",
      overview:
        "The CIA’s hunt is on for the mastermind of a wave of terrorist attacks. Roger Ferris is the agency’s man on the ground, moving from place to place, scrambling to stay ahead of ever-shifting events. An eye in the sky – a satellite link – watches Ferris.  At the other end of that real-time link is the CIA’s Ed Hoffman, strategizing events from thousands of miles away. And as Ferris nears the target, he discovers trust can be just as dangerous as it is necessary for survival.",
      posterPath: "/sLjVDPPfNQfAma9XyOqHPClQb2V.jpg",
      release_date: "2008-10-10",
      title: "Body of Lies",
      video: false,
      voteAverage: 6.6,
      vote_count: 2299,
      popularity: 14.484,
      character: "Roger Ferris",
      credit_id: "52fe44b79251416c7503e94f",
      order: 0,
    },
    {
      video: false,
      voteAverage: 6.6,
      overview:
        "Years have passed since the Three Musketeers, Aramis, Athos and Porthos, have fought together with their friend, D'Artagnan. But with the tyrannical King Louis using his power to wreak havoc in the kingdom while his twin brother, Philippe, remains imprisoned, the Musketeers reunite to abduct Louis and replace him with Philippe.",
      release_date: "1998-03-12",
      adult: false,
      backdrop_path: "/xzCe37rMKvYUnrAhIxpLJwv7Xmo.jpg",
      title: "The Man in the Iron Mask",
      genreIds: [12, 28, 18],
      id: 9313,
      original_language: "en",
      originalTitle: "The Man in the Iron Mask",
      posterPath: "/zHE9yRURvA7DyhYtQxkGTfE1Ywi.jpg",
      vote_count: 3024,
      popularity: 17.906,
      character: "King Louis XIV / Philippe",
      credit_id: "52fe44e6c3a36847f80b0935",
      order: 0,
    },
    {
      id: 27205,
      adult: false,
      backdrop_path: "/s3TBrRGB1iav7gFOCNx3H31MoES.jpg",
      title: "Inception",
      genreIds: [28, 878, 12],
      original_language: "en",
      originalTitle: "Inception",
      posterPath: "/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
      vote_count: 30095,
      video: false,
      voteAverage: 8.3,
      release_date: "2010-07-15",
      overview:
        "Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: \"inception\", the implantation of another person's idea into a target's subconscious.",
      popularity: 135.08,
      character: "Dom Cobb",
      credit_id: "52fe4534c3a368484e04de03",
      order: 0,
    },
    {
      adult: false,
      backdrop_path: "/3FYltaTkmrFeVquPOXbAXgYVuqZ.jpg",
      genreIds: [10749, 18],
      id: 36834,
      original_language: "en",
      originalTitle: "Total Eclipse",
      overview:
        "Young, wild poet Arthur Rimbaud and his mentor Paul Verlaine engage in a fierce, forbidden romance while feeling the effects of a hellish artistic lifestyle.",
      posterPath: "/e0j1zDF3ITeTbGTXFGamosCxT4z.jpg",
      release_date: "1995-11-03",
      title: "Total Eclipse",
      video: false,
      voteAverage: 6.4,
      vote_count: 385,
      popularity: 12.93,
      character: "Arthur Rimbaud",
      credit_id: "52fe460f9251416c91047b09",
      order: 0,
    },
    {
      adult: false,
      backdrop_path: "/qKbYJHQecf5QPLr57702msopoSs.jpg",
      genreIds: [99],
      id: 44992,
      original_language: "en",
      originalTitle: "IMAX Hubble",
      overview:
        "An IMAX 3D camera chronicles the effort of 7 astronauts aboard the Space Shuttle Atlantis to repair the Hubble Space Telescope.",
      posterPath: "/csUuK3fOCUanzjSNZGvFRZ8JdH4.jpg",
      release_date: "2010-03-19",
      title: "Hubble",
      video: false,
      voteAverage: 7.0,
      vote_count: 77,
      popularity: 4.783,
      character: "Narrator",
      credit_id: "52fe46a9c3a36847f810b255",
      order: 0,
    },
    {
      overview:
        "An adaptation of F. Scott Fitzgerald's Long Island-set novel, where Midwesterner Nick Carraway is lured into the lavish world of his neighbor, Jay Gatsby. Soon enough, however, Carraway will see through the cracks of Gatsby's nouveau riche existence, where obsession, madness, and tragedy await.",
      release_date: "2013-05-10",
      adult: false,
      backdrop_path: "/tb440cwQMRoVHnhYJlzlxfv1ikm.jpg",
      genreIds: [18, 10749],
      vote_count: 9961,
      original_language: "en",
      originalTitle: "The Great Gatsby",
      id: 64682,
      title: "The Great Gatsby",
      video: false,
      voteAverage: 7.4,
      posterPath: "/nimh1rrDDLhgpG8XAYoUZXHYwb6.jpg",
      popularity: 28.107,
      character: "Jay Gatsby",
      credit_id: "52fe46e3c3a368484e0a9783",
      order: 0,
    },
    {
      genreIds: [37, 18, 12],
      original_language: "en",
      originalTitle: "The Revenant",
      posterPath: "/ji3ecJphATlVgWNY0B0RVXZizdf.jpg",
      video: false,
      id: 281957,
      overview:
        "In the 1820s, a frontiersman, Hugh Glass, sets out on a path of vengeance against those who left him for dead after a bear mauling.",
      release_date: "2015-12-25",
      vote_count: 15055,
      voteAverage: 7.5,
      adult: false,
      backdrop_path: "/nMfH0LMMFk2ovyURkYvyTI99nSo.jpg",
      title: "The Revenant",
      popularity: 50.784,
      character: "Hugh Glass",
      credit_id: "53c3fe750e0a26157c00cada",
      order: 0,
    },
    {
      adult: false,
      backdrop_path: "/2qM3DsUILkozVy61eN0w7J64GOm.jpg",
      genreIds: [18, 80, 36],
      id: 88794,
      original_language: "en",
      originalTitle: "J. Edgar",
      overview:
        "As the face of law enforcement in the United States for almost 50 years, J. Edgar Hoover was feared and admired, reviled and revered. But behind closed doors, he held secrets that would have destroyed his image, his career, and his life.",
      posterPath: "/hWHFPhGvCvfHbZCxJSR3n6GsXIf.jpg",
      release_date: "2011-11-09",
      title: "J. Edgar",
      video: false,
      voteAverage: 6.2,
      vote_count: 1899,
      popularity: 9.777,
      character: "John Edgar Hoover",
      credit_id: "52fe4a039251416c910c04d9",
      order: 0,
    },
    {
      id: 106646,
      overview:
        "A New York stockbroker refuses to cooperate in a large securities fraud case involving corruption on Wall Street, corporate banking world and mob infiltration. Based on Jordan Belfort's autobiography.",
      release_date: "2013-12-25",
      adult: false,
      backdrop_path: "/cWUOv3H7YFwvKeaQhoAQTLLpo9Z.jpg",
      vote_count: 18485,
      genreIds: [80, 18, 35],
      voteAverage: 8.0,
      original_language: "en",
      originalTitle: "The Wolf of Wall Street",
      posterPath: "/pWHf4khOloNVfCxscsXFj3jj6gP.jpg",
      title: "The Wolf of Wall Street",
      video: false,
      popularity: 136.83,
      character: "Jordan Belfort",
      credit_id: "52fe4a6dc3a36847f81cd4e7",
      order: 0,
    },
    {
      adult: false,
      backdrop_path: "/mGBmiWmi7JqeTWnrPicRbkXcsuO.jpg",
      genreIds: [99],
      original_language: "en",
      originalTitle: "Before the Flood",
      posterPath: "/2fFTLaLbm8Ak7JBSYQ8Mb3jcFx9.jpg",
      vote_count: 633,
      video: false,
      voteAverage: 7.7,
      title: "Before the Flood",
      overview:
        "A look at how climate change affects our environment and what society can do to prevent the demise of endangered species, ecosystems, and native communities across the planet.",
      id: 410718,
      release_date: "2016-10-21",
      popularity: 21.161,
      character: "Self",
      credit_id: "57ecc67f925141356c006216",
      order: 0,
    },
    {
      id: 640,
      originalTitle: "Catch Me If You Can",
      posterPath: "/ctjEj2xM32OvBXCq8zAdK3ZrsAj.jpg",
      video: false,
      voteAverage: 7.9,
      overview:
        "A true story about Frank Abagnale Jr. who, before his 19th birthday, successfully conned millions of dollars worth of checks as a Pan Am pilot, doctor, and legal prosecutor. An FBI agent makes it his mission to put him behind bars. But Frank not only eludes capture, he revels in the pursuit.",
      release_date: "2002-12-25",
      vote_count: 11627,
      adult: false,
      backdrop_path: "/rwcEaZghpbt6mV0lRQ9ymz5oM9B.jpg",
      title: "Catch Me If You Can",
      genreIds: [18, 80],
      original_language: "en",
      popularity: 30.983,
      character: "Frank Abagnale Jr.",
      credit_id: "52fe4263c3a36847f801a63f",
      order: 0,
    },
    {
      adult: false,
      backdrop_path: "/tK8K6Mtq8aFAtrsq9FPx072oJla.jpg",
      genreIds: [80, 18, 53],
      id: 466420,
      original_language: "en",
      originalTitle: "Killers of the Flower Moon",
      overview:
        "Depicts the serial murder of members of the oil-wealthy Osage Nation in 1920s Oklahoma, a string of brutal crimes that came to be known as the Reign of Terror.",
      posterPath: null,
      release_date: "",
      title: "Killers of the Flower Moon",
      video: false,
      voteAverage: 0.0,
      vote_count: 0,
      popularity: 1.275,
      character: "Ernest Burkhart",
      credit_id: "5968f416c3a3686f60021bc8",
      order: 0,
    },
    {
      adult: false,
      backdrop_path: null,
      genreIds: [18],
      id: 329216,
      original_language: "en",
      originalTitle: "The Foot Shooting Party",
      overview:
        "The lead singer of a band gets drafted for war in Vietnam. So as not to break up the band, he decides to shoot his own foot.",
      posterPath: "/z4BbjUFclmQSu7X4sWZ8WKHIxNz.jpg",
      release_date: "1994-01-01",
      title: "The Foot Shooting Party",
      video: false,
      voteAverage: 5.0,
      vote_count: 8,
      popularity: 0.848,
      character: "Bud",
      credit_id: "59e392fc9251410b670003c0",
      order: 0,
    },
    {
      overview:
        "Los Angeles, 1969. TV star Rick Dalton, a struggling actor specializing in westerns, and stuntman Cliff Booth, his best friend, try to survive in a constantly changing movie industry. Dalton is the neighbor of the young and promising actress and model Sharon Tate, who has just married the prestigious Polish director Roman Polanski…",
      release_date: "2019-07-24",
      adult: false,
      backdrop_path: "/oRiUKwDpcqDdoLwPoA4FIRh3hqY.jpg",
      vote_count: 9461,
      genreIds: [35, 18, 53],
      id: 466272,
      original_language: "en",
      originalTitle: "Once Upon a Time… in Hollywood",
      posterPath: "/8j58iEBw9pOXFD2L0nt0ZXeHviB.jpg",
      title: "Once Upon a Time… in Hollywood",
      video: false,
      voteAverage: 7.5,
      popularity: 44.963,
      character: "Rick Dalton",
      credit_id: "5a12c204c3a368628306f0db",
      order: 0,
    },
    {
      video: false,
      voteAverage: 0.0,
      overview:
        "Two low-level astronomers, upon discovering that a meteor will strike the Earth in six months, go on a media tour to try to warn the world but find an unreceptive and unbelieving populace.",
      release_date: "2021-12-10",
      vote_count: 0,
      adult: false,
      backdrop_path: "/abG9ldrNqSEoguBsi9hmnjusJ0.jpg",
      id: 646380,
      genreIds: [35, 18, 878],
      title: "Don't Look Up",
      original_language: "en",
      originalTitle: "Don't Look Up",
      posterPath: "/m2wwiSHakki8BhRENmFZ2MelEJo.jpg",
      popularity: 17.411,
      character: "Dr. Randall Mindy",
      credit_id: "5f874bf3d4b9d90037273f96",
      order: 0,
    },
    {
      backdrop_path: "/fHuKwcrwltGlWn3510N1YO7vJ4I.jpg",
      genreIds: [10749, 18],
      original_language: "en",
      originalTitle: "What's Eating Gilbert Grape",
      posterPath: "/8FxWgsfDNosewo7H65oE4QkOb7g.jpg",
      id: 1587,
      video: false,
      voteAverage: 7.7,
      overview:
        "Gilbert Grape is a small-town young man with a lot of responsibility. Chief among his concerns are his mother, who is so overweight that she can't leave the house, and his mentally impaired younger brother, Arnie, who has a knack for finding trouble. Settled into a job at a grocery store and an ongoing affair with local woman Betty Carver, Gilbert finally has his life shaken up by the free-spirited Becky.",
      release_date: "1993-12-17",
      vote_count: 2959,
      title: "What's Eating Gilbert Grape",
      adult: false,
      popularity: 22.564,
      character: "Arnie Grape",
      credit_id: "52fe4301c3a36847f803368d",
      order: 1,
    },
    {
      voteAverage: 6.7,
      overview:
        "A leukemia patient attempts to end a 20-year feud with her sister to get her bone marrow.",
      release_date: "1996-12-18",
      adult: false,
      backdrop_path: "/dXGjxSaKV02s1It9i0IF7HhVQ8l.jpg",
      vote_count: 462,
      genreIds: [18],
      id: 9819,
      original_language: "en",
      originalTitle: "Marvin's Room",
      posterPath: "/89YFVzS7Unsb9knSKnVZJvGgeAz.jpg",
      title: "Marvin's Room",
      video: false,
      popularity: 7.473,
      character: "Hank",
      credit_id: "52fe4534c3a36847f80c1e31",
      order: 1,
    },
    {
      adult: false,
      backdrop_path: "/cDFtxTxEtE3ljadfQ5SwtRTi8Iw.jpg",
      genreIds: [18, 53, 80],
      original_language: "en",
      originalTitle: "The Departed",
      posterPath: "/kWWAt2FMRbqLFFy8o5R4Zr8cMAb.jpg",
      vote_count: 11683,
      video: false,
      title: "The Departed",
      voteAverage: 8.2,
      overview:
        "To take down South Boston's Irish Mafia, the police send in one of their own to infiltrate the underworld, not realizing the syndicate has done likewise. While an undercover cop curries favor with the mob kingpin, a career criminal rises through the police ranks. But both sides soon discover there's a mole among them.",
      release_date: "2006-10-05",
      id: 1422,
      popularity: 42.91,
      character: 'William "Billy" Costigan, Jr.',
      credit_id: "52fe42f5c3a36847f802fecf",
      order: 1,
    },
    {
      id: 365717,
      video: false,
      vote_count: 101,
      voteAverage: 6.3,
      title: "The Audition",
      release_date: "2015-10-03",
      original_language: "en",
      originalTitle: "The Audition",
      genreIds: [35],
      backdrop_path: "/54tR3SVqtoH80szs9M4YKJuJfGT.jpg",
      adult: false,
      overview:
        "Robert De Niro and Leonardo DiCaprio must compete for the lead role in Martin Scorsese's next film.",
      posterPath: "/t1PDIeDpJGgI9JPqIRMuG7WDdId.jpg",
      popularity: 5.694,
      character: "Himself",
      credit_id: "5630c9ffc3a3681b5e00f456",
      order: 1,
    },
    {
      id: 438425,
      video: false,
      vote_count: 0,
      voteAverage: 0.0,
      title: "The Black Hand",
      original_language: "en",
      originalTitle: "The Black Hand",
      genreIds: [18],
      backdrop_path: null,
      adult: false,
      overview:
        "Police officer, Joe Petrosino, seeks justice against a ruthless Italian-American gang in New York. A feature adaptation of Stephan Talty's book 'The Black Hand'.",
      posterPath: null,
      popularity: 0.6,
      character: "Joe Petrosino",
      credit_id: "5890f77b92514103ec00a871",
      order: 1,
    },
    {
      adult: false,
      backdrop_path: "/mEoU71g0SjTDEiMTyRj1bV2EfIp.jpg",
      genreIds: [99],
      id: 213362,
      original_language: "en",
      originalTitle: "Reflections on Titanic",
      overview:
        "An enthralling and fast-paced four-part documentary feature that covers the making of one of the last major Hollywood epics; Titanic. Cast and crew speak on setting the sinking of the ship against a classic romance. The feature also examines casting and the young couple headlining the film, DiCaprio's and Winslet's on-set friendship and their differing acting styles, the expansive sets and filming locations, the authenticity of the recreated ship, James Cameron's work and dedication, and budgeting. And many more aspects of the film are overviewed.",
      posterPath: null,
      release_date: "2012-09-10",
      title: "Reflections on Titanic",
      video: false,
      voteAverage: 7.2,
      vote_count: 19,
      popularity: 2.576,
      character: "Self",
      credit_id: "59e392fc9251410b670003a0",
      order: 1,
    },
    {
      adult: false,
      backdrop_path: null,
      genreIds: [18],
      id: 486010,
      original_language: "en",
      originalTitle: "Roosevelt",
      overview: "A biographical drama about President Theodore Roosevelt.",
      posterPath: null,
      release_date: "",
      title: "Roosevelt",
      video: false,
      voteAverage: 0.0,
      vote_count: 0,
      popularity: 0.96,
      character: "Theodore Roosevelt",
      credit_id: "5a03b301c3a3680fe7002a25",
      order: 1,
    },
    {
      id: 599379,
      video: false,
      vote_count: 38,
      voteAverage: 6.9,
      title: "Ice on Fire",
      release_date: "2019-06-23",
      original_language: "en",
      originalTitle: "Ice on Fire",
      genreIds: [99],
      backdrop_path: "/uDqyWBY1sMLUT5W3X89UYKv3coR.jpg",
      adult: false,
      overview:
        "An eye-opening documentary that asks the question: Are we going to let climate change destroy civilization, or will we act on technologies that can reverse it? Featuring never-before-seen solutions on the many ways we can reduce carbon in the atmosphere thus paving the way for temperatures to go down, saving civilization.",
      posterPath: "/9xWrasURZTWbSiulhyxCmJlYTkD.jpg",
      popularity: 6.316,
      character: "Self - Narrator",
      credit_id: "5cdd440bc3a368159dc1194e",
      order: 1,
    },
    {
      adult: false,
      backdrop_path: null,
      genreIds: [10751, 16, 35, 10402, 10770],
      id: 642488,
      original_language: "en",
      originalTitle: "Mickey's Safety Club: Street Safe, Street Smart",
      overview:
        "Mickey and his friends take a close look at important street safety situations and tips.",
      posterPath: "/4pfoP47sMClmkXwYYaUfb8gl08T.jpg",
      release_date: "1989-09-01",
      title: "Mickey's Safety Club: Street Safe, Street Smart",
      video: false,
      voteAverage: 9.8,
      vote_count: 18,
      popularity: 2.113,
      character: "Alex (voice)",
      credit_id: "5db3545c4b0c630017eba57d",
      order: 1,
    },
    {
      id: 669983,
      video: false,
      vote_count: 1,
      voteAverage: 7.0,
      title: "Teslafy Me",
      release_date: "2019-11-01",
      original_language: "en",
      originalTitle: "Teslafy Me",
      genreIds: [99, 36],
      backdrop_path: "/uP2EnC2XKUCXKlx3lk2yvcESOu0.jpg",
      adult: false,
      overview:
        "A vision for a world free of pollution and climate problems, with energy available in abundance - are we ready to take up legacy of ingenious inventor Nikola Tesla?",
      posterPath: "/c8w8xJG6roxYnLNVLWll5tvPYBg.jpg",
      popularity: 0.84,
      character: "Self",
      credit_id: "5ea9458b514c4a00268c866d",
      order: 1,
    },
    {
      id: 621751,
      video: false,
      vote_count: 8,
      voteAverage: 7.4,
      title: "And We Go Green",
      release_date: "2019-05-23",
      original_language: "en",
      originalTitle: "And We Go Green",
      genreIds: [99],
      backdrop_path: "/trZgJaml9vXosGtcZ2gw7gnjPbI.jpg",
      adult: false,
      overview:
        "Professional drivers on the international Formula E circuit — like Formula One, but with eco-friendly electric cars — race for victory across 10 cities.",
      posterPath: "/jO6IqXuWb8hY6145rhsNkRUewoz.jpg",
      popularity: 7.45,
      character: "Self",
      credit_id: "5ebaf191cc277c00206eefe7",
      order: 1,
    },
    {
      adult: false,
      backdrop_path: null,
      genreIds: [35, 18],
      id: 823102,
      original_language: "en",
      originalTitle: "Another Round",
      overview: "American remake of the Academy Award-winning Danish film.",
      posterPath: null,
      release_date: "",
      title: "Another Round",
      video: false,
      voteAverage: 0.0,
      vote_count: 0,
      popularity: 1.026,
      character: "",
      credit_id: "6087028a9a8a8a0041fb8fd7",
      order: 1,
    },
    {
      id: 64956,
      video: false,
      vote_count: 267,
      voteAverage: 7.3,
      title: "Inception: The Cobol Job",
      release_date: "2010-12-07",
      original_language: "en",
      originalTitle: "Inception: The Cobol Job",
      genreIds: [16, 28, 53, 878],
      backdrop_path: "/sABMpHRCmt7qg9q6AFbZ1jPU1Jf.jpg",
      adult: false,
      overview:
        "The Cobol Job is a fourteen-minute animated prequel to Christopher Nolan’s award-winning movie: Inception, detailing the heist on Mr. Kaneda's mind by Nash, Cobb, Arthur, and several Cobol Engineering thugs.",
      posterPath: "/sNxqwtyHMNQwKWoFYDqcYTui5Ok.jpg",
      popularity: 8.983,
      character: "Cobb",
      credit_id: "60d40d77e9c0dc00265721b1",
      order: 1,
    },
    {
      adult: false,
      backdrop_path: null,
      genreIds: [],
      id: 656423,
      original_language: "en",
      originalTitle: "Portrait of Leonardo: The Kid Who Took Hollywood",
      overview: "A documentary on Leonardo Dicaprio.",
      posterPath: "/zQYiolbmx6S3wFmnrp1IkRjPWzo.jpg",
      release_date: "",
      title: "Portrait of Leonardo: The Kid Who Took Hollywood",
      video: false,
      voteAverage: 0.0,
      vote_count: 0,
      popularity: 0.6,
      character: "Himself",
      credit_id: "612ac5c2a1d3320094f3ce04",
      order: 1,
    },
    {
      adult: false,
      backdrop_path: "/6N6VUUR1gzbCkiGpQzvRREv3Od1.jpg",
      genreIds: [18],
      id: 8092,
      original_language: "en",
      originalTitle: "This Boy's Life",
      overview:
        "When a son and mother move to Seattle in hopes for a better life, the mother meets a seemingly polite man. Things go south when the man turns out to be abusive, endangering their lives. As the mother struggles to maintain hope in an impossible situation, the son has plans to escape.",
      posterPath: "/hmSIhx180f0ADcpaQisVXYRB6Fr.jpg",
      release_date: "1993-04-09",
      title: "This Boy's Life",
      video: false,
      voteAverage: 7.1,
      vote_count: 708,
      popularity: 10.162,
      character: "Tobias Wolff",
      credit_id: "52fe4493c3a36847f809dcd5",
      order: 2,
    },
    {
      adult: false,
      backdrop_path: "/2oZklIzUbvZXXzIFzv7Hi68d6xf.jpg",
      genreIds: [18, 37],
      vote_count: 21411,
      original_language: "en",
      originalTitle: "Django Unchained",
      posterPath: "/7oWY8VDWW7thTzWh3OKYRkWUlD5.jpg",
      title: "Django Unchained",
      video: false,
      id: 68718,
      voteAverage: 8.1,
      overview:
        "With the help of a German bounty hunter, a freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.",
      release_date: "2012-12-25",
      popularity: 64.953,
      character: "Calvin J. Candie",
      credit_id: "52fe479fc3a368484e0d12db",
      order: 2,
    },
    {
      adult: false,
      backdrop_path: null,
      genreIds: [99],
      id: 696842,
      original_language: "en",
      originalTitle: "Scorsese's Goodfellas",
      overview:
        "In this produced by Brett Ratner new retrospective documentary we hear from cast members and additional participants include Harvey Keitel, Leonardo DiCaprio and Terence Winter, creator of Boardwalk Empire and screenwriter of The Wolf of Wall Street. The program gives us thoughts about Scorsese's approach to the material, casting, characters, and performances, costumes and period details, photography, music, and retrospective thoughts about the film. It is filled with memorable stories and observations from a wide array of commentators.",
      posterPath: "/eQPjyYlRduhxDP7To0kMfMaOkiU.jpg",
      release_date: "2015-05-05",
      title: "Scorsese's Goodfellas",
      video: true,
      voteAverage: 7.8,
      vote_count: 8,
      popularity: 1.725,
      character: "Himself",
      credit_id: "5ea369c73faba00025455101",
      order: 2,
    },
    {
      adult: false,
      backdrop_path: "/1Q0FrRbywFPjseam7mwt6MYKXe7.jpg",
      genreIds: [99],
      id: 402970,
      original_language: "en",
      originalTitle: "Notes on an American Film Director at Work",
      overview:
        "Filmmaker Jonas Mekas follows his friend, film director Martin Scorsese, and his cast and crew, through various locations during the shooting of his film The Departed, released in 2006.",
      posterPath: "/8Ah2goGOhoR1i7jwOOaie10reoS.jpg",
      release_date: "2008-01-01",
      title: "Notes on an American Film Director at Work",
      video: false,
      voteAverage: 5.0,
      vote_count: 1,
      popularity: 3.233,
      character: "Self",
      credit_id: "5ebdb25a6d675a00207a4e8b",
      order: 2,
    },
    {
      genreIds: [37, 28, 53],
      title: "The Quick and the Dead",
      original_language: "en",
      originalTitle: "The Quick and the Dead",
      posterPath: "/fQk89YaQdeBcS7AmlKODKOxIAPU.jpg",
      video: false,
      voteAverage: 6.5,
      id: 12106,
      release_date: "1995-02-09",
      vote_count: 1219,
      adult: false,
      backdrop_path: "/wwdzmWC1Ra9SqPBrtCyRNJ4oYUO.jpg",
      overview:
        "A mysterious woman comes to compete in a quick-draw elimination tournament, in a town taken over by a notorious gunman.",
      popularity: 11.216,
      character: "Fee Herod 'The Kid'",
      credit_id: "52fe44b69251416c7503e5a7",
      order: 3,
    },
    {
      adult: false,
      backdrop_path: "/5NaM9m6lA5JcIZolbNWvUCgsIeV.jpg",
      genreIds: [18, 35],
      id: 9466,
      original_language: "en",
      originalTitle: "Celebrity",
      overview:
        "The career and personal life of writer Lee are at a standstill, so he divorces his bashful wife, Robin, and dives into a new job as an entertainment journalist. His assignments take him to the swankiest corners of Manhattan, but as he jumps from one lavish party to another and engages in numerous empty romances, he starts to doubt the worth of his work. Meanwhile, top TV producer Tony falls for Robin and introduces her to the world of celebrity.",
      posterPath: "/3pbcMORRjqYgfx87CXexLw32gk.jpg",
      release_date: "1998-09-07",
      title: "Celebrity",
      video: false,
      voteAverage: 6.0,
      vote_count: 330,
      popularity: 12.121,
      character: "Brandon",
      credit_id: "52fe44fbc3a36847f80b59b3",
      order: 3,
    },
    {
      video: false,
      voteAverage: 5.1,
      overview:
        "In what appears to be a cross between Critters and The Towering Inferno, the residents of a shoddy L.A. apartment block are chased up to the roof by hoards of the eponymous hairy horrors.",
      release_date: "1991-12-11",
      vote_count: 246,
      adult: false,
      backdrop_path: "/kb0jFY1rDTxQeJRt1HJs2SQZdiz.jpg",
      title: "Critters 3",
      genreIds: [35, 27, 878],
      id: 12702,
      original_language: "en",
      originalTitle: "Critters 3",
      posterPath: "/frjklbq23pRgBjhekEq6drQkrZm.jpg",
      popularity: 14.752,
      character: "Josh",
      credit_id: "52fe45169251416c7504b579",
      order: 3,
    },
    {
      adult: false,
      backdrop_path: "/7xrlSPGDO4CDT6IHTctDlkYxTzw.jpg",
      genreIds: [18],
      id: 37857,
      original_language: "en",
      originalTitle: "Don's Plum",
      overview:
        "A group of Los Angeles teenagers meet every day at their local diner hangout to discus their latest misadventures with their miserable lives",
      posterPath: "/pXWiYyWaNUfZaud5maDWDFJ5AG7.jpg",
      release_date: "2001-02-10",
      title: "Don's Plum",
      video: false,
      voteAverage: 5.7,
      vote_count: 55,
      popularity: 7.38,
      character: "Derek",
      credit_id: "59e392fc9251410b6700039a",
      order: 3,
    },
    {
      adult: false,
      backdrop_path: "/f9oNiTUoharENGjdDufG0aDbSIO.jpg",
      genreIds: [53, 18],
      id: 9264,
      original_language: "en",
      originalTitle: "Poison Ivy",
      overview:
        "A seductive teen befriends an introverted high school student and schemes her way into the lives of her wealthy family.",
      posterPath: "/igwGf0qNka1qH1HPijgbABfUfB4.jpg",
      release_date: "1992-05-08",
      title: "Poison Ivy",
      video: false,
      voteAverage: 5.4,
      vote_count: 242,
      popularity: 15.113,
      character: "Guy",
      credit_id: "59e392fc9251410b67000398",
      order: 4,
    },
    {
      genreIds: [99],
      original_language: "en",
      originalTitle: "The Wolf Pack",
      posterPath: "/b9YeaSCQulFSDgD965CzQo9tmsi.jpg",
      video: true,
      title: "The Wolf Pack",
      vote_count: 5,
      overview:
        "Extra for The Wolf Of Wall Street featuring Leonardo DiCaprio, Martin Scorsese, Jonah Hill and more as they take fans behind-the-scenes during the making of the film and also discuss the real-life Belfort and his trajectory in the world of moneymaking.",
      release_date: "2014-03-20",
      voteAverage: 7.6,
      id: 259465,
      adult: false,
      backdrop_path: null,
      popularity: 1.252,
      character: "Himself",
      credit_id: "610f910fe63571002d1cfc35",
      order: 4,
    },
    {
      adult: false,
      backdrop_path: null,
      genreIds: [99],
      id: 459682,
      original_language: "en",
      originalTitle: "Catch Me If You Can: Behind the Camera",
      overview:
        "A behind the scenes look at the making of Stephen Spielberg's Catch Me If You Can.",
      posterPath: "/wQXvOy2hpfLscTorrzhy2icveVZ.jpg",
      release_date: "2003-05-06",
      title: "Catch Me If You Can: Behind the Camera",
      video: false,
      voteAverage: 8.7,
      vote_count: 12,
      popularity: 1.333,
      character: "Himself",
      credit_id: "59e392fc9251410b670003be",
      order: 5,
    },
    {
      id: 402967,
      video: false,
      vote_count: 8,
      voteAverage: 7.9,
      title: "Koko: The Gorilla Who Talks to People",
      release_date: "2016-06-15",
      original_language: "en",
      originalTitle: "Koko: The Gorilla Who Talks to People",
      genreIds: [99],
      backdrop_path: null,
      adult: false,
      overview:
        "Documentary telling the extraordinary story of Koko, the only 'talking' gorilla in the world, and her lifelong relationship with Penny Patterson. Project Koko started as a PhD project to teach sign language to a baby gorilla, but as Koko began to communicate with Penny, an intense bond formed between them. Penny has now been with Koko for over 40 years and claims Koko can reveal fresh insights into the workings of an animal's mind. Koko's unique life with Penny has been filmed every step of the way. Over 2,000 hours of footage chart the most dramatic moments - Penny's battle to keep Koko from being taken back to the zoo in which she was born, Penny's clash with academic critics who doubted her claims and the image of Koko mourning the death of her kitten.",
      posterPath: "/ltZNA9hf1Aj7aStQovtSShyHRDS.jpg",
      popularity: 1.251,
      character: "Self",
      credit_id: "6124fc2f31644b0045639d0d",
      order: 5,
    },
    {
      backdrop_path: "/hoML3xQNqd6aRcUXiVlPhrSIfAR.jpg",
      genreIds: [99, 10770],
      title: "Spielberg",
      original_language: "en",
      originalTitle: "Spielberg",
      posterPath: "/2AAvIR2PHoxNITgLDOkXXlWLlua.jpg",
      id: 467062,
      video: false,
      voteAverage: 7.5,
      overview:
        "A documentary on the life and career of one of the most influential film directors of all time, Steven Spielberg.",
      release_date: "2017-10-05",
      vote_count: 198,
      adult: false,
      popularity: 11.022,
      character: "Self",
      credit_id: "59dc0ef3c3a368620d05bb6f",
      order: 6,
    },
    {
      original_language: "en",
      originalTitle: "The 11th Hour",
      posterPath: "/9ZQyqJhoqSXYhu27oRDqz3Tzl10.jpg",
      video: false,
      voteAverage: 6.9,
      overview:
        "A look at the state of the global environment including visionary and practical solutions for restoring the planet's ecosystems. Featuring ongoing dialogues of experts from all over the world, including former Soviet Prime Minister Mikhail Gorbachev, renowned scientist Stephen Hawking, former head of the CIA R. James Woolse",
      release_date: "2007-08-17",
      vote_count: 69,
      title: "The 11th Hour",
      adult: false,
      backdrop_path: "/rf1a61N3QGiXVUwC19WV3TRfwOO.jpg",
      id: 4832,
      genreIds: [99],
      popularity: 6.419,
      character: "Himself",
      credit_id: "59e392fc9251410b670003a2",
      order: 6,
    },
    {
      id: 379053,
      video: false,
      vote_count: 14,
      voteAverage: 6.1,
      title: "A World Unseen: The Revenant",
      release_date: "2016-01-21",
      original_language: "en",
      originalTitle: "A World Unseen: The Revenant",
      genreIds: [99],
      backdrop_path: "/5EX5VvLGBM02RulMyn7YJWJJsKH.jpg",
      adult: false,
      overview:
        "A new documentary directed by Eliot Rausch exploring the production of Alejandro G. Iñárritu's The Revenant",
      posterPath: "/p0ZLWJzw6FAWtKv30pwsTA4zI08.jpg",
      popularity: 2.544,
      character: "Himself",
      credit_id: "59e392fc9251410b670003a8",
      order: 6,
    },
    {
      adult: false,
      backdrop_path: "/3rw5aaSAzE64mdkeOk6N3KPlSWJ.jpg",
      genreIds: [99],
      original_language: "en",
      originalTitle: "Leonardo DiCaprio: Most Wanted!",
      id: 792166,
      vote_count: 8,
      title: "Leonardo DiCaprio: Most Wanted!",
      voteAverage: 7.8,
      video: false,
      overview:
        "From his juvenile, tormented, heroic roles, which made him a global phenomenon, to his darker mature roles, a portrait of American actor Leonardo DiCaprio, a consummate performer and probably the most successful film star of his generation.",
      release_date: "2021-01-29",
      posterPath: "/oO8CotrnqhHAGbVMcCqNHrb89pP.jpg",
      popularity: 2.097,
      character: "Self - Actor (archive footage)",
      credit_id: "603627d4223e20003f043074",
      order: 6,
    },
    {
      video: true,
      voteAverage: 7.0,
      overview:
        "A documentary about the making of Martin Scorsese's 'The Departed' and its influences.",
      release_date: "2007-04-25",
      adult: false,
      backdrop_path: null,
      vote_count: 1,
      genreIds: [99],
      title: "Crossing Criminal Cultures",
      original_language: "en",
      originalTitle: "Crossing Criminal Cultures",
      posterPath: "/oSReXz9rJ2W4esTS8cHP76MBI49.jpg",
      id: 615443,
      popularity: 0.95,
      character: "Himself",
      credit_id: "5d2b1c1fa294f042db2bfd77",
      order: 7,
    },
    {
      adult: false,
      backdrop_path: null,
      genreIds: [35],
      id: 803107,
      original_language: "ja",
      originalTitle: "JAPANARAMA! Psycho TV From Japan Vol. 1",
      overview:
        "No wonder the Japanese are such a stressed-out society: They enjoy mutilating and torturing each other just for the hell of it...not to mention for the benefits of the television cameras, and Japanarama! Volume 1 captures two hours of only the very twisted of psycho TV from Japan. Much of this party tape utilizes footage from bizarre and cruel game shows. Rounding out the tape are some great cheesey commercials, mostly for foods that look grossly unappetizing, and some with sell out American celebrities. A few scenes are shown from various weird Far East movies.",
      posterPath: "/2jdhkjw3qQ5BJq4Vkv5BuQ6fAEV.jpg",
      release_date: "",
      title: "JAPANARAMA! Psycho TV From Japan Vol. 1",
      video: true,
      voteAverage: 0.0,
      vote_count: 0,
      popularity: 0.6,
      character: "",
      credit_id: "6043b06a2b8a43005798afe9",
      order: 10,
    },
    {
      adult: false,
      backdrop_path: null,
      genreIds: [],
      id: 376478,
      original_language: "en",
      originalTitle: "X-Girl",
      overview:
        "A short film created to promote Kim Gordon and Daisy von Furth's second collection for their clothing line, X-Girl.",
      posterPath: "/ygg8JjT9LIr9J0DOM8GT4xjSNwS.jpg",
      release_date: "1995-01-01",
      title: "X-Girl",
      video: false,
      voteAverage: 3.0,
      vote_count: 1,
      popularity: 0.6,
      character: "Himself (uncredited)",
      credit_id: "5dd3e0a7b39e3500138c9267",
      order: 12,
    },
    {
      id: 36863,
      video: false,
      vote_count: 6,
      voteAverage: 7.5,
      title: "Everything's Cool",
      release_date: "2007-01-01",
      original_language: "en",
      originalTitle: "Everything's Cool",
      genreIds: [99],
      backdrop_path: "/9zje9bA21EQuY9MHcGWCl2coApS.jpg",
      adult: false,
      overview:
        'In this documentary, filmmakers Daniel B. Gold and Judith Helfand (Blue Vinyl) follow a troupe of self-proclaimed global warming "warriors" on a mission to get the world to care about rising temperatures and melting polar ice caps. Taking a topic that\'s inherently serious and applying their signature blend of humor and emotional heft, Gold and Helfand advance the environmental dialogue in a surprisingly entertaining way.',
      posterPath: "/3Au8x9Yq1W9dssEFQBKPDacvSOz.jpg",
      popularity: 1.8,
      character: "Self (archive footage)",
      credit_id: "5f962ac6fcf9070037e99dc3",
      order: 15,
    },
    {
      originalTitle: "kid 90",
      id: 795859,
      video: false,
      voteAverage: 7.5,
      overview:
        "As a teenager in the '90s, Soleil Moon Frye carried a video camera everywhere she went. She documented hundreds of hours of footage and then locked it away for over 20 years.",
      release_date: "2021-03-12",
      vote_count: 23,
      adult: false,
      backdrop_path: "/dtnVDcsXzpkFeij8J6IkNEQI2hY.jpg",
      title: "kid 90",
      genreIds: [99],
      posterPath: "/5yK7ySo3E3w1JDjqq9WNk9oIwsw.jpg",
      original_language: "en",
      popularity: 5.291,
      character: "Self (archive footage)",
      credit_id: "6075edce3f4833002972d82a",
      order: 15,
    },
    {
      adult: false,
      backdrop_path: "/4W3Y8V9AA8kU8ngiPF2BexnQqPC.jpg",
      genreIds: [99],
      id: 818082,
      original_language: "fr",
      originalTitle: "Salvator mundi",
      overview:
        "In November 15, 2017, the painting Salvator Mundi, attributed to Italian artist Leonardo da Vinci (1452-1519), was sold for an unprecedented $450 million. An examination of the dirty secrets of the art world and the surprising story of how a work of art is capable of upsetting both personal and geopolitical interests.",
      posterPath: "/oXgSXAnhFRsn3ze49jtSae6srQt.jpg",
      release_date: "2021-06-12",
      title: "The Savior for Sale",
      video: false,
      voteAverage: 6.0,
      vote_count: 3,
      popularity: 1.186,
      character: "Self - Actor (archive footage)",
      credit_id: "611cd3282e0697005da113e2",
      order: 18,
    },
    {
      backdrop_path: "/ulKw0ytuwp9L2RmikvO3mg8Ll6b.jpg",
      overview:
        "A detailed account of the life and artistic career of legendary filmmaker Quentin Tarantino, from his early days as a video club manager to the scandalous fall in disgrace of producer Harvey Weinstein. A story about how to shoot eight great movies and become an icon of modern pop culture.",
      genreIds: [99],
      original_language: "en",
      originalTitle: "QT8: The First Eight",
      posterPath: "/rGPwMYUeygsUAmo0NS8IPlhQEfH.jpg",
      id: 631143,
      title: "QT8: The First Eight",
      voteAverage: 7.3,
      vote_count: 83,
      release_date: "2019-10-21",
      video: false,
      adult: false,
      popularity: 7.941,
      character: "Self (archive footage)",
      credit_id: "60d4f33563a69500465099b6",
      order: 20,
    },
    {
      adult: false,
      backdrop_path: "/5cFrRDLgf030lB7dzvlE8qONURr.jpg",
      genreIds: [99, 36],
      id: 822099,
      original_language: "en",
      originalTitle: "The Lost Leonardo",
      overview:
        "London, England, 2008. Some of the most distinguished experts on the work of Italian artist Leonardo da Vinci (1452-1519) gather at the National Gallery to examine a painting known as Salvator Mundi; an event that turns out to be the first act of one of the most fascinating stories in the history of art.",
      posterPath: "/nVXECwOa4g5ZHND6dOxXjQ5bbpT.jpg",
      release_date: "2021-08-20",
      title: "The Lost Leonardo",
      video: false,
      voteAverage: 5.0,
      vote_count: 1,
      popularity: 5.131,
      character: "Self - Actor (archive footage)",
      credit_id: "61455f7bdaf57c008abb356c",
      order: 27,
    },
    {
      id: 75009,
      video: false,
      vote_count: 4,
      voteAverage: 4.0,
      title: "The Concert for New York City",
      release_date: "2001-10-20",
      original_language: "en",
      originalTitle: "The Concert for New York City",
      genreIds: [99, 36, 10402],
      backdrop_path: null,
      adult: false,
      overview:
        "The Concert for New York City took place on October 20, 2001 at Madison Square Garden. It was a celebration of the strength of New York and a thank-you to the heroic firefighters, police officers and rescue workers who saved tens of thousands of lives on September 11th. More than 6000 firefighters, police officers and rescue workers attended as guests.",
      posterPath: "/rq0LTMvPdBTxkjW2ka3HOOT5bet.jpg",
      popularity: 4.467,
      character: "Self",
      credit_id: "5b8f195b925141739b00252f",
      order: 29,
    },
  ],
  crew: [
    {
      title: "The Assassination of Richard Nixon",
      voteAverage: 6.6,
      overview:
        "It’s 1974 and Sam Bicke has lost everything. His wife leaves him with his three kids, his boss fires him, his brother turns away from him, and the bank won’t give him any money to start anew. He tries to find someone to blame for his misfortunes and comes up with the President of the United States who he plans to murder.",
      release_date: "2004-05-17",
      adult: false,
      backdrop_path: "/gXvmhujLzYRXMQPZNBDFUD3RnEg.jpg",
      vote_count: 218,
      genreIds: [18, 36, 53],
      id: 842,
      original_language: "en",
      originalTitle: "The Assassination of Richard Nixon",
      posterPath: "/5jOOvAVvP0XtwC5yYQpQCy4cjq1.jpg",
      video: false,
      popularity: 11.016,
      credit_id: "52fe4280c3a36847f8023e8b",
      department: "Production",
      job: "Executive Producer",
    },
    {
      adult: false,
      backdrop_path: "/nxPpDLO1sYlOqpNdL4Pc7athIlu.jpg",
      genreIds: [18],
      id: 10316,
      original_language: "en",
      originalTitle: "The Ides of March",
      overview:
        "Dirty tricks stand to soil an ambitious young press spokesman's idealism in a cutthroat presidential campaign where 'victory' is relative.",
      posterPath: "/w8t4UnJnC24S9ygoaFgmMzRbErd.jpg",
      release_date: "2011-09-24",
      title: "The Ides of March",
      video: false,
      voteAverage: 6.7,
      vote_count: 1919,
      popularity: 10.101,
      credit_id: "52fe43589251416c7500cc6d",
      department: "Production",
      job: "Executive Producer",
    },
    {
      original_language: "en",
      originalTitle: "The 11th Hour",
      posterPath: "/9ZQyqJhoqSXYhu27oRDqz3Tzl10.jpg",
      video: false,
      voteAverage: 6.9,
      overview:
        "A look at the state of the global environment including visionary and practical solutions for restoring the planet's ecosystems. Featuring ongoing dialogues of experts from all over the world, including former Soviet Prime Minister Mikhail Gorbachev, renowned scientist Stephen Hawking, former head of the CIA R. James Woolse",
      release_date: "2007-08-17",
      vote_count: 69,
      title: "The 11th Hour",
      adult: false,
      backdrop_path: "/rf1a61N3QGiXVUwC19WV3TRfwOO.jpg",
      id: 4832,
      genreIds: [99],
      popularity: 6.419,
      credit_id: "52fe43ddc3a36847f8074d69",
      department: "Production",
      job: "Producer",
    },
    {
      release_date: "2009-07-24",
      genreIds: [27, 53, 9648],
      adult: false,
      original_language: "en",
      originalTitle: "Orphan",
      posterPath: "/lCGpOgoTOGLtZnBiGY9HRg5Xnjd.jpg",
      video: false,
      voteAverage: 6.9,
      id: 21208,
      vote_count: 3814,
      title: "Orphan",
      backdrop_path: "/yrR1Hk2NbWupDHfroGt2spdE1Jm.jpg",
      overview:
        "After losing their baby, a married couple adopt 9-year old Esther, who may not be as innocent as she seems.",
      popularity: 81.307,
      credit_id: "52fe440fc3a368484e00d3b9",
      department: "Production",
      job: "Producer",
    },
    {
      adult: false,
      backdrop_path: null,
      genreIds: [35, 18],
      id: 25354,
      original_language: "en",
      originalTitle: "Gardener of Eden",
      overview:
        "When a young deli-counter clerk and general slacker in New Jersey accidentally saves a young woman from a serial rapist, he becomes convinced that his new role in life is to become a vigilante.",
      posterPath: "/6Vq91cEOicwNKMqlLtYmg1WPdW.jpg",
      release_date: "2007-04-26",
      title: "Gardener of Eden",
      video: false,
      voteAverage: 6.0,
      vote_count: 20,
      popularity: 4.72,
      credit_id: "52fe44c3c3a368484e0356f7",
      department: "Production",
      job: "Producer",
    },
    {
      id: 106646,
      overview:
        "A New York stockbroker refuses to cooperate in a large securities fraud case involving corruption on Wall Street, corporate banking world and mob infiltration. Based on Jordan Belfort's autobiography.",
      release_date: "2013-12-25",
      adult: false,
      backdrop_path: "/cWUOv3H7YFwvKeaQhoAQTLLpo9Z.jpg",
      vote_count: 18485,
      genreIds: [80, 18, 35],
      voteAverage: 8.0,
      original_language: "en",
      originalTitle: "The Wolf of Wall Street",
      posterPath: "/pWHf4khOloNVfCxscsXFj3jj6gP.jpg",
      title: "The Wolf of Wall Street",
      video: false,
      popularity: 136.83,
      credit_id: "52fe4a6dc3a36847f81cd4d1",
      department: "Production",
      job: "Producer",
    },
    {
      id: 164457,
      overview:
        "Two brothers live in the economically-depressed Rust Belt, when a cruel twist of fate lands one in prison. His brother is then lured into one of the most violent crime rings in the Northeast.",
      release_date: "2013-12-06",
      adult: false,
      backdrop_path: "/hxBTaMW9qkZ4LG5ZnPxMoHZOk9K.jpg",
      vote_count: 1514,
      genreIds: [53, 18, 80],
      voteAverage: 6.6,
      original_language: "en",
      originalTitle: "Out of the Furnace",
      posterPath: "/cOuQQ4eRpSBxb0G9OXzWE1pHPeq.jpg",
      title: "Out of the Furnace",
      video: false,
      popularity: 11.531,
      credit_id: "52fe4c7ac3a36847f82304ab",
      department: "Production",
      job: "Producer",
    },
    {
      genreIds: [12, 28, 53],
      original_language: "en",
      originalTitle: "Robin Hood",
      posterPath: "/AiRfixFcfTkNbn2A73qVJPlpkUo.jpg",
      video: false,
      voteAverage: 5.9,
      title: "Robin Hood",
      overview:
        "A war-hardened Crusader and his Moorish commander mount an audacious revolt against the corrupt English crown.",
      release_date: "2018-11-21",
      vote_count: 2364,
      adult: false,
      backdrop_path: "/zSJT1sKGRKcmP4I9b8dIOuepw6I.jpg",
      id: 375588,
      popularity: 25.448,
      credit_id: "59a65be2c3a368280f008355",
      department: "Production",
      job: "Producer",
    },
    {
      adult: false,
      backdrop_path: "/zfaajfDILOqfC6cbfjDy4a7obp6.jpg",
      genreIds: [14, 53, 27],
      id: 49730,
      original_language: "en",
      originalTitle: "Red Riding Hood",
      overview:
        "Valerie is in love with a brooding outsider, Peter, but her parents have arranged for her to marry another man – who is wealthy. Unwilling to lose each other, Valerie and Peter plan to run away together when they learn that Valerie's older sister has been killed by a werewolf that prowls the dark forest surrounding their village. Hungry for revenge, the people call on famed werewolf hunter, Father Solomon, to help them kill the wolf. But Solomon's arrival brings unintended consequences as he warns that the wolf, who takes human form by day, could be any one of them.",
      posterPath: "/ixQYkLeLlTTnAoT32dukndyObB6.jpg",
      release_date: "2011-03-11",
      title: "Red Riding Hood",
      video: false,
      voteAverage: 6.0,
      vote_count: 2654,
      popularity: 25.087,
      credit_id: "53675f5ac3a3681220004476",
      department: "Production",
      job: "Producer",
    },
    {
      genreIds: [18],
      original_language: "en",
      originalTitle: "The Aviator",
      posterPath: "/lx4kWcZc3o9PaNxlQpEJZM17XUI.jpg",
      video: false,
      voteAverage: 7.2,
      vote_count: 4108,
      overview:
        "A biopic depicting the life of filmmaker and aviation pioneer Howard Hughes from 1927 to 1947, during which time he became a successful film producer and an aviation magnate, while simultaneously growing more unstable due to severe obsessive-compulsive disorder.",
      id: 2567,
      release_date: "2004-12-17",
      title: "The Aviator",
      adult: false,
      backdrop_path: "/dFs5aShkZWiaeM7bHbn2tK5o8Zh.jpg",
      popularity: 19.573,
      credit_id: "5573120b925141318e002459",
      department: "Production",
      job: "Executive Producer",
    },
    {
      adult: false,
      backdrop_path: null,
      genreIds: [18],
      id: 346683,
      original_language: "en",
      originalTitle: "Wilson",
      overview:
        "A look at the role U.S. President Woodrow Wilson played in World War I.",
      posterPath: null,
      release_date: "",
      title: "Wilson",
      video: false,
      voteAverage: 0.0,
      vote_count: 0,
      popularity: 0.6,
      credit_id: "5590cca0925141758300007b",
      department: "Production",
      job: "Producer",
    },
    {
      adult: false,
      backdrop_path: "/mGBmiWmi7JqeTWnrPicRbkXcsuO.jpg",
      genreIds: [99],
      original_language: "en",
      originalTitle: "Before the Flood",
      posterPath: "/2fFTLaLbm8Ak7JBSYQ8Mb3jcFx9.jpg",
      vote_count: 633,
      video: false,
      voteAverage: 7.7,
      title: "Before the Flood",
      overview:
        "A look at how climate change affects our environment and what society can do to prevent the demise of endangered species, ecosystems, and native communities across the planet.",
      id: 410718,
      release_date: "2016-10-21",
      popularity: 21.161,
      credit_id: "57ecc6cb9251410c5b00d2c5",
      department: "Production",
      job: "Executive Producer",
    },
    {
      overview:
        "Wildlife activists and investigators put their lives on the line to battle the illegal African ivory trade, in this suspenseful on-the-ground documentary.",
      release_date: "2016-09-02",
      adult: false,
      backdrop_path: "/fHkDtfR9u4tDfL803OOtTwfDqhF.jpg",
      genreIds: [99],
      vote_count: 49,
      original_language: "en",
      originalTitle: "The Ivory Game",
      id: 411023,
      title: "The Ivory Game",
      video: false,
      voteAverage: 7.6,
      posterPath: "/dWFyOj0wk8AFLqC8PH5LRD3kJht.jpg",
      popularity: 6.788,
      credit_id: "581f9178c3a3685553004726",
      department: "Production",
      job: "Executive Producer",
    },
    {
      adult: false,
      backdrop_path: "/rfHyl8C2ghhahZUtxYLvK9ru4zK.jpg",
      genreIds: [80, 18, 53],
      id: 259695,
      original_language: "en",
      originalTitle: "Live by Night",
      overview:
        "A story set in the Prohibition Era and centered on a group of individuals and their dealings in the world of organized crime.",
      posterPath: "/7kxSjMrjJIXqgFMAT4CvKF5nnF6.jpg",
      release_date: "2016-12-25",
      title: "Live by Night",
      video: false,
      voteAverage: 6.2,
      vote_count: 1056,
      popularity: 16.957,
      credit_id: "5846be30c3a368490300b526",
      department: "Production",
      job: "Producer",
    },
    {
      id: 438425,
      video: false,
      vote_count: 0,
      voteAverage: 0.0,
      title: "The Black Hand",
      original_language: "en",
      originalTitle: "The Black Hand",
      genreIds: [18],
      backdrop_path: null,
      adult: false,
      overview:
        "Police officer, Joe Petrosino, seeks justice against a ruthless Italian-American gang in New York. A feature adaptation of Stephan Talty's book 'The Black Hand'.",
      posterPath: null,
      popularity: 0.6,
      credit_id: "5890f7d4c3a368702400a96f",
      department: "Production",
      job: "Producer",
    },
    {
      adult: false,
      backdrop_path: "/zAfG4ZmpNfKSyr8MVn1CHjgYYXx.jpg",
      genreIds: [18, 36, 80],
      vote_count: 1695,
      original_language: "en",
      originalTitle: "Richard Jewell",
      posterPath: "/5Lgkm8jt4roAFPZQ52fKMhVmDaZ.jpg",
      title: "Richard Jewell",
      video: false,
      voteAverage: 7.5,
      release_date: "2019-12-13",
      overview:
        "Richard Jewell thinks quick, works fast, and saves hundreds, perhaps thousands, of lives after a domestic terrorist plants several pipe bombs and they explode during a concert, only to be falsely suspected of the crime by sloppy FBI work and sensational media coverage.",
      id: 292011,
      popularity: 14.874,
      credit_id: "593e09e59251416945011b3b",
      department: "Production",
      job: "Producer",
    },
    {
      adult: false,
      backdrop_path: "/bRQUXL1GRRLrkH183eS81CUk4Kj.jpg",
      genreIds: [80, 53, 18],
      id: 146238,
      original_language: "en",
      originalTitle: "Runner Runner",
      overview:
        "When a poor college student who cracks an online poker game goes bust, he arranges a face-to-face with the man he thinks cheated him, a sly offshore entrepreneur.",
      posterPath: "/7xZY1BZWIgkKI2zSfE9qHiADaOF.jpg",
      release_date: "2013-09-24",
      title: "Runner Runner",
      video: false,
      voteAverage: 5.7,
      vote_count: 992,
      popularity: 10.359,
      credit_id: "5972914bc3a36815930249b1",
      department: "Production",
      job: "Producer",
    },
    {
      original_language: "en",
      originalTitle: "Cowspiracy: The Sustainability Secret",
      posterPath: "/5rn3jsTgqQWPQRDof3eHT3wd500.jpg",
      video: false,
      voteAverage: 7.8,
      overview:
        "Follow the shocking, yet humorous, journey of an aspiring environmentalist, as he daringly seeks to find the real solution to the most pressing environmental issues and true path to sustainability.",
      release_date: "2014-07-01",
      vote_count: 385,
      id: 282297,
      adult: false,
      backdrop_path: "/7KYqBgUtQGInqHVEMRnlyneuCpA.jpg",
      title: "Cowspiracy: The Sustainability Secret",
      genreIds: [99],
      popularity: 11.157,
      credit_id: "5b10bdc60e0a26307c00e2dc",
      department: "Production",
      job: "Executive Producer",
    },
    {
      adult: false,
      backdrop_path: null,
      genreIds: [99],
      id: 339161,
      original_language: "en",
      originalTitle: "Catching the Sun",
      overview:
        "An unemployed American worker, a Tea Party activist, and a Chinese solar entrepreneur. But who wins and who loses the battle for power in the 21st century? Through interwoven character dramas spanning the U.S. and China, Catching the Sun explores the global economic race to lead the clean energy future.",
      posterPath: "/bH27INYEvDCD38aJ816aowcCncX.jpg",
      release_date: "2015-06-12",
      title: "Catching the Sun",
      video: false,
      voteAverage: 7.2,
      vote_count: 12,
      popularity: 1.96,
      credit_id: "5b31dda20e0a26401400b390",
      department: "Production",
      job: "Executive Producer",
    },
    {
      voteAverage: 8.0,
      overview:
        "Virunga in the Democratic Republic of the Congo is Africa’s oldest national park, a UNESCO world heritage site, and a contested ground among insurgencies seeking to topple the government that see untold profits in the land. Among this ongoing power struggle, Virunga also happens to be the last natural habitat for the critically endangered mountain gorilla. The only thing standing in the way of the forces closing in around the gorillas: a handful of passionate park rangers and journalists fighting to secure the park’s borders and expose the corruption of its enemies. Filled with shocking footage, and anchored by the surprisingly deep and gentle characters of the gorillas themselves, Virunga is a galvanizing call to action around an ongoing political and environmental crisis in the Congo.",
      release_date: "2014-11-07",
      adult: false,
      backdrop_path: "/pmhPTJnEJhvvZhK92cfCpnE3TqZ.jpg",
      vote_count: 169,
      genreIds: [99, 10752],
      video: false,
      original_language: "en",
      originalTitle: "Virunga",
      posterPath: "/b59YdJZyRUu04hnWdmmz4kPjbTF.jpg",
      id: 263614,
      title: "Virunga",
      popularity: 6.135,
      credit_id: "5b31ddd1c3a368533500a420",
      department: "Production",
      job: "Executive Producer",
    },
    {
      video: false,
      voteAverage: 7.8,
      overview:
        "A documentary focused on plastic pollution in the world's oceans.",
      release_date: "2016-09-22",
      adult: false,
      backdrop_path: "/bQGDBSxjovzlOpOnqK6g3HVcAID.jpg",
      vote_count: 66,
      genreIds: [99],
      id: 431339,
      original_language: "en",
      originalTitle: "A Plastic Ocean",
      posterPath: "/8Ry1c7rVYonb4y8ELpdxvvMQWB1.jpg",
      title: "A Plastic Ocean",
      popularity: 5.378,
      credit_id: "5b31ddf90e0a263ffc00a3d5",
      department: "Production",
      job: "Executive Producer",
    },
    {
      adult: false,
      backdrop_path: "/oO7jZXPbzjvc4F5icsYqFGHzqSr.jpg",
      genreIds: [53, 27],
      id: 340601,
      original_language: "en",
      originalTitle: "Delirium",
      overview:
        "A man recently released from a mental institute inherits a mansion after his parents die. After a series of disturbing events, he comes to believe it is haunted.",
      posterPath: "/j2jIkjrASnjtwCmCNDwh9LDWvq9.jpg",
      release_date: "2018-05-10",
      title: "Delirium",
      video: false,
      voteAverage: 5.7,
      vote_count: 177,
      popularity: 8.434,
      credit_id: "5b31de3cc3a368532200b2bd",
      department: "Production",
      job: "Producer",
    },
    {
      adult: false,
      backdrop_path: null,
      genreIds: [18],
      id: 486010,
      original_language: "en",
      originalTitle: "Roosevelt",
      overview: "A biographical drama about President Theodore Roosevelt.",
      posterPath: null,
      release_date: "",
      title: "Roosevelt",
      video: false,
      voteAverage: 0.0,
      vote_count: 0,
      popularity: 0.96,
      credit_id: "5b31de7c0e0a26400a00a6bd",
      department: "Production",
      job: "Producer",
    },
    {
      adult: false,
      backdrop_path: null,
      genreIds: [12, 18, 9648],
      id: 331042,
      original_language: "en",
      originalTitle: "The Deep Blue Good-By",
      overview: "Detective Travis McGee sets out to locate a WWII treasure.",
      posterPath: null,
      release_date: "",
      title: "The Deep Blue Good-By",
      video: false,
      voteAverage: 8.3,
      vote_count: 4,
      popularity: 0.6,
      credit_id: "5b31dee29251413c9b009b8f",
      department: "Production",
      job: "Producer",
    },
    {
      adult: false,
      backdrop_path: null,
      genreIds: [],
      id: 505675,
      original_language: "en",
      originalTitle: "Harker",
      overview:
        "Evil rules the night. It spreads its black hand across the land. No one is safe from its wrath and sooner or later it will devour everyone. One man has made it his purpose to journey into the heart of hell and face the devil himself to take back what is rightfully his. This is the story of Jonathan Harker. This Orlando based team have challenged themselves to create a silent film in HARKER, a puppet short. They have gone to great lengths to re-create the true feeling of a silent movie. Puppets are created with an exceptional visual style, much like the German Expressionists films The Cabinet of Dr. Caligari and Nosferatu.",
      posterPath: null,
      release_date: "",
      title: "Harker",
      video: false,
      voteAverage: 8.5,
      vote_count: 2,
      popularity: 1.158,
      credit_id: "5b31e04c0e0a26400a00a78f",
      department: "Production",
      job: "Producer",
    },
    {
      original_language: "en",
      originalTitle: "Struggle: The Life and Lost Art of Szukalski",
      posterPath: "/uvBJHkVGLwAqUbiNtxsUfVITBcT.jpg",
      video: false,
      voteAverage: 7.7,
      overview:
        "The remarkable life story of the pre-war Polish artist Stanislav Szukalski, documented by the American friends he made late in life.",
      release_date: "2018-12-21",
      vote_count: 52,
      id: 565255,
      adult: false,
      backdrop_path: "/x16W2mBhIoAmMn8Ds1GHqE2AnWh.jpg",
      title: "Struggle: The Life and Lost Art of Szukalski",
      genreIds: [99],
      popularity: 5.044,
      credit_id: "5c47cf919251415e3451e17a",
      department: "Production",
      job: "Producer",
    },
    {
      id: 599379,
      video: false,
      vote_count: 38,
      voteAverage: 6.9,
      title: "Ice on Fire",
      release_date: "2019-06-23",
      original_language: "en",
      originalTitle: "Ice on Fire",
      genreIds: [99],
      backdrop_path: "/uDqyWBY1sMLUT5W3X89UYKv3coR.jpg",
      adult: false,
      overview:
        "An eye-opening documentary that asks the question: Are we going to let climate change destroy civilization, or will we act on technologies that can reverse it? Featuring never-before-seen solutions on the many ways we can reduce carbon in the atmosphere thus paving the way for temperatures to go down, saving civilization.",
      posterPath: "/9xWrasURZTWbSiulhyxCmJlYTkD.jpg",
      popularity: 6.316,
      credit_id: "5ccacc70925141044e24de56",
      department: "Production",
      job: "Producer",
    },
    {
      adult: false,
      backdrop_path: null,
      genreIds: [12, 10751],
      id: 548699,
      original_language: "en",
      originalTitle: "Captain Planet",
      overview:
        "A story centered around an environmentally friendly superhero.",
      posterPath: null,
      release_date: "",
      title: "Captain Planet",
      video: false,
      voteAverage: 0.0,
      vote_count: 0,
      popularity: 0.84,
      credit_id: "5d317750caab6d1640a41373",
      department: "Production",
      job: "Producer",
    },
    {
      id: 621751,
      video: false,
      vote_count: 8,
      voteAverage: 7.4,
      title: "And We Go Green",
      release_date: "2019-05-23",
      original_language: "en",
      originalTitle: "And We Go Green",
      genreIds: [99],
      backdrop_path: "/trZgJaml9vXosGtcZ2gw7gnjPbI.jpg",
      adult: false,
      overview:
        "Professional drivers on the international Formula E circuit — like Formula One, but with eco-friendly electric cars — race for victory across 10 cities.",
      posterPath: "/jO6IqXuWb8hY6145rhsNkRUewoz.jpg",
      popularity: 7.45,
      credit_id: "5d4c4f90c68b6900140fc8f2",
      department: "Production",
      job: "Producer",
    },
    {
      overview:
        "The vaquita, the world’s smallest whale, is nearing extinction as its habitat is destroyed  by Mexican cartels and the Chinese Mafia, who harvest the totoaba fish, the “cocaine of the sea.” Environmental activists, the Mexican navy, and undercover investigators are fighting back against this illegal multimillion-dollar business.",
      release_date: "2019-09-20",
      adult: false,
      backdrop_path: "/3fwEwcrPjDCPzRpOXtc1KAQ6PDA.jpg",
      genreIds: [99],
      vote_count: 43,
      original_language: "en",
      originalTitle: "Sea of Shadows",
      posterPath: "/8qUT6hgWwAZCrB4Df5d4pygYmmR.jpg",
      title: "Sea of Shadows",
      video: false,
      voteAverage: 7.8,
      id: 566219,
      popularity: 8.686,
      credit_id: "5da5258c8a88b20011c6f995",
      department: "Production",
      job: "Executive Producer",
    },
    {
      id: 668344,
      video: false,
      vote_count: 0,
      voteAverage: 0.0,
      title: "The Corporation",
      release_date: "",
      original_language: "en",
      originalTitle: "The Corporation",
      genreIds: [28, 80, 53],
      backdrop_path: null,
      adult: false,
      overview:
        'A story of Jose Miguel Battle (a.k.a. the Godfather), the leader of an organized crime group, called "The Corporation", which was involved in illegal activities ranging from loansharking and gambling to drug trafficking and murder.',
      posterPath: null,
      popularity: 0.6,
      credit_id: "5e33ab5598f1f10014014356",
      department: "Production",
      job: "Producer",
    },
    {
      adult: false,
      backdrop_path: null,
      genreIds: [],
      id: 718375,
      original_language: "en",
      originalTitle: "Untitled Barry Jenkins 'Virunga' Adaptation",
      overview:
        "A feature adaptation of the 2014 Oscar-nominated documentary VIRUNGA.",
      posterPath: null,
      release_date: "",
      title: "Untitled Barry Jenkins 'Virunga' Adaptation",
      video: false,
      voteAverage: 0.0,
      vote_count: 0,
      popularity: 0.6,
      credit_id: "5ef249c143cd5400337aa537",
      department: "Production",
      job: "Producer",
    },
    {
      adult: false,
      backdrop_path: "/avjz9a8wyh09JyuIcjIWMA75yyD.jpg",
      genreIds: [99],
      id: 451474,
      original_language: "en",
      originalTitle: "The Last Shaman",
      overview:
        'James, giving himself 12 months before he has "a license to kill himself," sets off to the Amazon rainforest with hopes of finding a shaman who can save his life.',
      posterPath: "/52wrrla3cOVadcNNBNf3HVKeX7d.jpg",
      release_date: "2017-05-12",
      title: "The Last Shaman",
      video: false,
      voteAverage: 7.0,
      vote_count: 19,
      popularity: 4.694,
      credit_id: "601709f1cb8028003f148f63",
      department: "Production",
      job: "Executive Producer",
    },
    {
      originalTitle: "kid 90",
      id: 795859,
      video: false,
      voteAverage: 7.5,
      overview:
        "As a teenager in the '90s, Soleil Moon Frye carried a video camera everywhere she went. She documented hundreds of hours of footage and then locked it away for over 20 years.",
      release_date: "2021-03-12",
      vote_count: 23,
      adult: false,
      backdrop_path: "/dtnVDcsXzpkFeij8J6IkNEQI2hY.jpg",
      title: "kid 90",
      genreIds: [99],
      posterPath: "/5yK7ySo3E3w1JDjqq9WNk9oIwsw.jpg",
      original_language: "en",
      popularity: 5.291,
      credit_id: "60342785c6006d003db9bd4e",
      department: "Production",
      job: "Executive Producer",
    },
    {
      adult: false,
      backdrop_path: null,
      genreIds: [35, 18],
      id: 823102,
      original_language: "en",
      originalTitle: "Another Round",
      overview: "American remake of the Academy Award-winning Danish film.",
      posterPath: null,
      release_date: "",
      title: "Another Round",
      video: false,
      voteAverage: 0.0,
      vote_count: 0,
      popularity: 1.026,
      credit_id: "608702c255c926007826aa81",
      department: "Production",
      job: "Producer",
    },
    {
      posterPath: "/ocrHHmxHTu4gz8iWaGYzkUAXUyJ.jpg",
      title: "The Loneliest Whale: The Search for 52",
      voteAverage: 8.5,
      overview:
        "THE LONELIEST WHALE is a cinematic quest to find the “52 Hertz Whale,” which scientists believe has spent its entire life in solitude calling out at a frequency that is different from any other whale. As the film embarks on this engrossing journey, audiences will explore what this whale’s lonely plight can teach us — not just about our changing relationship to the oceans, but to each other. Executive Produced with Leonardo DiCaprio and Adrian Grenier.",
      release_date: "2021-07-09",
      vote_count: 4,
      adult: false,
      backdrop_path: "/1lABZ9jKQ7u0GmmJaqK9EOCQrOb.jpg",
      video: false,
      genreIds: [99],
      id: 821546,
      original_language: "en",
      originalTitle: "The Loneliest Whale: The Search for 52",
      popularity: 2.047,
      credit_id: "60c13b441ac2920076ac1a84",
      department: "Production",
      job: "Executive Producer",
    },
    {
      release_date: "2021-07-13",
      id: 844584,
      backdrop_path: null,
      genreIds: [99],
      vote_count: 2,
      original_language: "en",
      originalTitle: "Fin",
      posterPath: "/zsURBSQ6RnrTHm3v5L08wLiNHQj.jpg",
      title: "Fin",
      video: false,
      voteAverage: 5.0,
      adult: false,
      overview:
        "Follows a group of scientists, researchers and activist exposing the extinction behind sharks.",
      popularity: 2.397,
      credit_id: "60d5023ea6d93100739a2119",
      department: "Production",
      job: "Executive Producer",
    },
    {
      original_language: "en",
      originalTitle: "The 11th Hour",
      posterPath: "/9ZQyqJhoqSXYhu27oRDqz3Tzl10.jpg",
      video: false,
      voteAverage: 6.9,
      overview:
        "A look at the state of the global environment including visionary and practical solutions for restoring the planet's ecosystems. Featuring ongoing dialogues of experts from all over the world, including former Soviet Prime Minister Mikhail Gorbachev, renowned scientist Stephen Hawking, former head of the CIA R. James Woolse",
      release_date: "2007-08-17",
      vote_count: 69,
      title: "The 11th Hour",
      adult: false,
      backdrop_path: "/rf1a61N3QGiXVUwC19WV3TRfwOO.jpg",
      id: 4832,
      genreIds: [99],
      popularity: 6.419,
      credit_id: "52fe43ddc3a36847f8074d5d",
      department: "Writing",
      job: "Screenplay",
    },
    {
      adult: false,
      backdrop_path: null,
      genreIds: [],
      id: 718375,
      original_language: "en",
      originalTitle: "Untitled Barry Jenkins 'Virunga' Adaptation",
      overview:
        "A feature adaptation of the 2014 Oscar-nominated documentary VIRUNGA.",
      posterPath: null,
      release_date: "",
      title: "Untitled Barry Jenkins 'Virunga' Adaptation",
      video: false,
      voteAverage: 0.0,
      vote_count: 0,
      popularity: 0.6,
      credit_id: "60819c49c439c0002a3bf862",
      department: "Writing",
      job: "Writer",
    },
  ],
  id: 6193,
};

const photos = {
  id: 6193,
  profiles: [
    {
      aspect_ratio: 0.667,
      height: 1563,
      iso_639_1: null,
      file_path: "/posters/titanic/response.jpeg",
      voteAverage: 5.62,
      vote_count: 22,
      width: 1042,
    },
    {
      aspect_ratio: 0.666,
      height: 1640,
      iso_639_1: null,
      file_path: "/posters/titanic/response_1.jpeg",
      voteAverage: 5.346,
      vote_count: 17,
      width: 1093,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: null,
      file_path: "/posters/titanic/response_2.jpeg",
      voteAverage: 5.282,
      vote_count: 14,
      width: 2000,
    },
    {
      aspect_ratio: 0.667,
      height: 2190,
      iso_639_1: null,
      file_path: "/posters/titanic/response_3.jpeg",
      voteAverage: 5.276,
      vote_count: 12,
      width: 1460,
    },
    {
      aspect_ratio: 0.666,
      height: 1481,
      iso_639_1: null,
      file_path: "/posters/titanic/response_4.jpeg",
      voteAverage: 5.276,
      vote_count: 12,
      width: 987,
    },
    {
      aspect_ratio: 0.667,
      height: 750,
      iso_639_1: null,
      file_path: "/posters/titanic/response.jpeg",
      voteAverage: 5.19,
      vote_count: 5,
      width: 500,
    },
  ],
}.profiles.splice(0, 5);

movies = movies.cast
  ?.sort((film, filmB) => filmB.voteAverage - film.voteAverage)
  .slice(0, 10);

movies.map((film, indexFilm) => {
  return film.genreIds.map((categorie, indexCategorie) => {
    const filter = genres.find((genre) => genre.id === categorie);
    movies[indexFilm].genreIds[indexCategorie] = filter.name;
    return filter.name;
  });
});
export { person, movies, photos };
