const movie = {
  adult: false,
  backdrop_path: "/6VmFqApQRyZZzmiGOQq2C92jyvH.jpg",
  belongs_to_collection: null,
  budget: 200000000,
  genres: [
    {
      id: 18,
      name: "Drama",
    },
    {
      id: 10749,
      name: "Romance",
    },
  ],
  homepage: "",
  id: 597,
  imdb_id: "tt0120338",
  original_language: "en",
  original_title: "Titanic",
  overview:
    "101-year-old Rose DeWitt Bukater tells the story of her life aboard the Titanic, 84 years later. A young Rose boards the ship with her mother and fiancé. Meanwhile, Jack Dawson and Fabrizio De Rossi win third-class tickets aboard the ship. Rose tells the whole story from Titanic's departure through to its death—on its first and last voyage—on April 15, 1912.",
  popularity: 102.676,
  poster_path: "/posters/titanic/poster_titanic.jpeg",
  production_companies: [
    {
      id: 4,
      logo_path: "/fycMZt242LVjagMByZOLUGbCvv3.png",
      name: "Paramount",
      origin_country: "US",
    },
    {
      id: 574,
      logo_path: "/iB6GjNVHs5hOqcEYt2rcjBqIjki.png",
      name: "Lightstorm Entertainment",
      origin_country: "US",
    },
    {
      id: 25,
      logo_path: "/qZCc1lty5FzX30aOCVRBLzaVmcp.png",
      name: "20th Century Fox",
      origin_country: "US",
    },
  ],
  production_countries: [
    {
      iso_3166_1: "US",
      name: "United States of America",
    },
  ],
  release_date: "1997-11-18",
  revenue: 2187463944,
  runtime: 194,
  spoken_languages: [
    {
      english_name: "English",
      iso_639_1: "en",
      name: "English",
    },
    {
      english_name: "French",
      iso_639_1: "fr",
      name: "Français",
    },
    {
      english_name: "German",
      iso_639_1: "de",
      name: "Deutsch",
    },
    {
      english_name: "Swedish",
      iso_639_1: "sv",
      name: "svenska",
    },
    {
      english_name: "Italian",
      iso_639_1: "it",
      name: "Italiano",
    },
    {
      english_name: "Russian",
      iso_639_1: "ru",
      name: "Pусский",
    },
  ],
  status: "Released",
  tagline: "Nothing on Earth could come between them.",
  title: "Titanic",
  video: false,
  vote_average: 7.9,
  vote_count: 19931,
};

const credits = {
  id: 597,
  cast: [
    {
      adult: false,
      gender: 2,
      id: 6193,
      known_for_department: "Acting",
      name: "Leonardo DiCaprio",
      original_name: "Leonardo DiCaprio",
      popularity: 23.614,
      profile_path: "/posters/titanic/Leo.jpeg",
      cast_id: 21,
      character: "Jack Dawson",
      credit_id: "52fe425ac3a36847f80179cf",
      order: 0,
    },
    {
      adult: false,
      gender: 1,
      id: 204,
      known_for_department: "Acting",
      name: "Kate Winslet",
      original_name: "Kate Winslet",
      popularity: 14.919,
      profile_path: "/posters/titanic/Kate.jpeg",
      cast_id: 20,
      character: "Rose DeWitt Bukater",
      credit_id: "52fe425ac3a36847f80179cb",
      order: 1,
    },
    {
      adult: false,
      gender: 2,
      id: 1954,
      known_for_department: "Acting",
      name: "Billy Zane",
      original_name: "Billy Zane",
      popularity: 15.999,
      profile_path: "/posters/titanic/bill.jpeg",
      cast_id: 23,
      character: "Cal Hockley",
      credit_id: "52fe425ac3a36847f80179d7",
      order: 2,
    },
    {
      adult: false,
      gender: 1,
      id: 8534,
      known_for_department: "Acting",
      name: "Kathy Bates",
      original_name: "Kathy Bates",
      popularity: 9.516,
      profile_path: "/posters/titanic/Kathy.jpeg",
      cast_id: 24,
      character: "Molly Brown",
      credit_id: "52fe425ac3a36847f80179db",
      order: 3,
    },
    {
      adult: false,
      gender: 1,
      id: 3713,
      known_for_department: "Acting",
      name: "Frances Fisher",
      original_name: "Frances Fisher",
      popularity: 5.595,
      profile_path: "/posters/titanic/bill.jpeg",
      cast_id: 22,
      character: "Ruth Dewitt Bukater",
      credit_id: "52fe425ac3a36847f80179d3",
      order: 4,
    },
  ],
};

const images = {
  backdrops: [
    {
      aspect_ratio: 1.778,
      height: 1080,
      iso_639_1: null,
      file_path: "/6VmFqApQRyZZzmiGOQq2C92jyvH.jpg",
      vote_average: 5.522,
      vote_count: 6,
      width: 1920,
    },
  ],
  id: 597,
  logos: [
    {
      aspect_ratio: 4.614,
      height: 277,
      iso_639_1: "en",
      file_path: "/posters/titanic/krest.jpeg",
      vote_average: 5.312,
      vote_count: 1,
      width: 1278,
    },
    {
      aspect_ratio: 5.707,
      height: 116,
      iso_639_1: "en",
      file_path: "/posters/titanic/withLogo.jpeg",
      vote_average: 5.312,
      vote_count: 1,
      width: 662,
    },
    {
      aspect_ratio: 4.477,
      height: 285,
      iso_639_1: "en",
      file_path: "/posters/titanic/onBoat.jpeg",
      vote_average: 0.0,
      vote_count: 0,
      width: 1276,
    },
  ],
  posters: [
    {
      aspect_ratio: 0.667,
      height: 1500,
      iso_639_1: "en",
      file_path: "/posters/titanic/krest.jpeg",
      vote_average: 5.648,
      vote_count: 8,
      width: 1000,
    },
    {
      aspect_ratio: 0.667,
      height: 2398,
      iso_639_1: "fr",
      file_path: "/posters/titanic/onBoat.jpeg",
      vote_average: 5.39,
      vote_count: 6,
      width: 1600,
    },
    {
      aspect_ratio: 0.667,
      height: 1500,
      iso_639_1: "ru",
      file_path: "/posters/titanic/krest.jpeg",
      vote_average: 5.388,
      vote_count: 4,
      width: 1000,
    },
    {
      aspect_ratio: 0.667,
      height: 1440,
      iso_639_1: "en",
      file_path: "/posters/titanic/withLogo.jpeg",
      vote_average: 5.388,
      vote_count: 4,
      width: 960,
    },
    {
      aspect_ratio: 0.706,
      height: 1700,
      iso_639_1: "it",
      file_path: "/posters/titanic/krest.jpeg",
      vote_average: 5.384,
      vote_count: 2,
      width: 1200,
    },
    {
      aspect_ratio: 0.667,
      height: 1500,
      iso_639_1: "uk",
      file_path: "/posters/titanic/withLogo.jpeg",
      vote_average: 5.384,
      vote_count: 2,
      width: 1000,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: "en",
      file_path: "/posters/titanic/krest.jpeg",
      vote_average: 5.384,
      vote_count: 2,
      width: 2000,
    },
    {
      aspect_ratio: 0.666,
      height: 1501,
      iso_639_1: "en",
      file_path: "/posters/titanic/withLogo.jpeg",
      vote_average: 5.318,
      vote_count: 3,
      width: 1000,
    },
    {
      aspect_ratio: 0.667,
      height: 1500,
      iso_639_1: "he",
      file_path: "/posters/titanic/withLogo.jpeg",
      vote_average: 5.312,
      vote_count: 1,
      width: 1000,
    },
    {
      aspect_ratio: 0.667,
      height: 1500,
      iso_639_1: "he",
      file_path: "/posters/titanic/withLogo.jpeg",
      vote_average: 5.312,
      vote_count: 1,
      width: 1000,
    },
    {
      aspect_ratio: 0.667,
      height: 1500,
      iso_639_1: "en",
      file_path: "/zraTDtulFw2wrpyuYf646k95MNq.jpg",
      vote_average: 5.312,
      vote_count: 1,
      width: 1000,
    },
    {
      aspect_ratio: 0.699,
      height: 1689,
      iso_639_1: "ko",
      file_path: "/p0L1f5YRiUmbExUTn5VbFQtxfpN.jpg",
      vote_average: 5.312,
      vote_count: 1,
      width: 1181,
    },
    {
      aspect_ratio: 0.666,
      height: 1426,
      iso_639_1: "ru",
      file_path: "/mA0Dcp327JOX1YoaQS5nqXjDoyW.jpg",
      vote_average: 5.312,
      vote_count: 1,
      width: 950,
    },
    {
      aspect_ratio: 0.667,
      height: 2100,
      iso_639_1: "de",
      file_path: "/MlnPG3oxhfmuiDwcoeElQWui9m.jpg",
      vote_average: 5.312,
      vote_count: 1,
      width: 1400,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: "th",
      file_path: "/zOE6uP7iKDA4mJDeXYiWcZA7cJe.jpg",
      vote_average: 5.312,
      vote_count: 1,
      width: 2000,
    },
    {
      aspect_ratio: 0.707,
      height: 2162,
      iso_639_1: "en",
      file_path: "/5YBQwsEmIdtzRtN9h2C2SV6c6J2.jpg",
      vote_average: 5.27,
      vote_count: 10,
      width: 1528,
    },
    {
      aspect_ratio: 0.667,
      height: 1500,
      iso_639_1: "en",
      file_path: "/AbuyfKTHDp7oHxpMKgtEaIZqoU9.jpg",
      vote_average: 5.258,
      vote_count: 6,
      width: 1000,
    },
    {
      aspect_ratio: 0.7,
      height: 1428,
      iso_639_1: "th",
      file_path: "/KiI4tAIUdm7Qu39YT3GOI23Xsu.jpg",
      vote_average: 5.246,
      vote_count: 2,
      width: 1000,
    },
    {
      aspect_ratio: 0.667,
      height: 1800,
      iso_639_1: "fr",
      file_path: "/bQTIHseOK7X64RUdilmoaJpU5sg.jpg",
      vote_average: 5.246,
      vote_count: 2,
      width: 1200,
    },
    {
      aspect_ratio: 0.667,
      height: 1500,
      iso_639_1: "ru",
      file_path: "/vtMrH3fSJBvhhQOCAseIVbFtZvO.jpg",
      vote_average: 5.246,
      vote_count: 2,
      width: 1000,
    },
    {
      aspect_ratio: 0.666,
      height: 3000,
      iso_639_1: "de",
      file_path: "/iJGnyJ5A9CHWvrbbtFfiEvxH2Co.jpg",
      vote_average: 5.246,
      vote_count: 2,
      width: 1999,
    },
    {
      aspect_ratio: 0.667,
      height: 1500,
      iso_639_1: "en",
      file_path: "/i4Tx0pTUyeMeFmCrMaL2WRTg6qB.jpg",
      vote_average: 5.246,
      vote_count: 2,
      width: 1000,
    },
    {
      aspect_ratio: 0.667,
      height: 1500,
      iso_639_1: "en",
      file_path: "/2YuK1oc6fzaMBjYxjBkHZhBcSLr.jpg",
      vote_average: 5.246,
      vote_count: 2,
      width: 1000,
    },
    {
      aspect_ratio: 0.667,
      height: 2100,
      iso_639_1: "fr",
      file_path: "/UeFdEWlZp2E7n4asNl0UlKzhka.jpg",
      vote_average: 5.246,
      vote_count: 2,
      width: 1400,
    },
    {
      aspect_ratio: 0.721,
      height: 1664,
      iso_639_1: "de",
      file_path: "/uA9vpdIn0XRwnw1jUVekj4aFwxY.jpg",
      vote_average: 5.246,
      vote_count: 2,
      width: 1200,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: "en",
      file_path: "/1GP8ppg8JCpxyd6jOZOk44TO8U7.jpg",
      vote_average: 5.198,
      vote_count: 7,
      width: 2000,
    },
    {
      aspect_ratio: 0.667,
      height: 1500,
      iso_639_1: "en",
      file_path: "/dvWYPmOrydx2T65egoCOD3YGabU.jpg",
      vote_average: 5.19,
      vote_count: 5,
      width: 1000,
    },
    {
      aspect_ratio: 0.667,
      height: 1371,
      iso_639_1: "uk",
      file_path: "/uxRdYnFxMJpY4WGMQsKSron9z3f.jpg",
      vote_average: 5.18,
      vote_count: 3,
      width: 914,
    },
    {
      aspect_ratio: 0.667,
      height: 3000,
      iso_639_1: "en",
      file_path: "/74d4bOZ7kwUHEjb5NZ84Ft6lCpR.jpg",
      vote_average: 5.18,
      vote_count: 3,
      width: 2000,
    },
    {
      aspect_ratio: 0.667,
      height: 1200,
      iso_639_1: "en",
      file_path: "/6MB3BlevLWRv4zDT4VicZETsOKc.jpg",
      vote_average: 5.18,
      vote_count: 3,
      width: 800,
    },
    {
      aspect_ratio: 0.736,
      height: 1400,
      iso_639_1: "ko",
      file_path: "/t0EqhsC3UYeTYhYnrxwvhBo1uOV.jpg",
      vote_average: 5.172,
      vote_count: 1,
      width: 1030,
    },
    {
      aspect_ratio: 0.706,
      height: 1000,
      iso_639_1: "bg",
      file_path: "/yfIx0ZXPMyiiNZHDq1HOyukt2kX.jpg",
      vote_average: 5.172,
      vote_count: 1,
      width: 706,
    },
    {
      aspect_ratio: 0.667,
      height: 750,
      iso_639_1: "es",
      file_path: "/rVBIfNJZcTITcVbvgmtyPOF8CzD.jpg",
      vote_average: 5.172,
      vote_count: 1,
      width: 500,
    },
    {
      aspect_ratio: 0.714,
      height: 1681,
      iso_639_1: "ja",
      file_path: "/9THZ0bjPRc4qP229dmItJcQTQKU.jpg",
      vote_average: 5.172,
      vote_count: 1,
      width: 1200,
    },
  ],
};

export { movie, credits, images };
