const movie = {
  adult: false,
  backdrop_path: "/6VmFqApQRyZZzmiGOQq2C92jyvH.jpg",
  belongs_to_collection: null,
  budget: 200000000,
  genres: [
    {
      id: 18,
      name: "Drama",
    },
    {
      id: 10749,
      name: "Romance",
    },
  ],
  homepage: "",
  id: 597,
  imdb_id: "tt0120338",
  original_language: "en",
  original_title: "Titanic",
  overview:
    "101-year-old Rose DeWitt Bukater tells the story of her life aboard the Titanic, 84 years later. A young Rose boards the ship with her mother and fiancé. Meanwhile, Jack Dawson and Fabrizio De Rossi win third-class tickets aboard the ship. Rose tells the whole story from Titanic's departure through to its death—on its first and last voyage—on April 15, 1912.",
  popularity: 102.676,
  poster_path: "/9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg",
  production_companies: [
    {
      id: 4,
      logo_path: "/fycMZt242LVjagMByZOLUGbCvv3.png",
      name: "Paramount",
      origin_country: "US",
    },
    {
      id: 574,
      logo_path: "/iB6GjNVHs5hOqcEYt2rcjBqIjki.png",
      name: "Lightstorm Entertainment",
      origin_country: "US",
    },
    {
      id: 25,
      logo_path: "/qZCc1lty5FzX30aOCVRBLzaVmcp.png",
      name: "20th Century Fox",
      origin_country: "US",
    },
  ],
  production_countries: [
    {
      iso_3166_1: "US",
      name: "United States of America",
    },
  ],
  release_date: "1997-11-18",
  revenue: 2187463944,
  runtime: 194,
  spoken_languages: [
    {
      english_name: "English",
      iso_639_1: "en",
      name: "English",
    },
    {
      english_name: "French",
      iso_639_1: "fr",
      name: "Français",
    },
    {
      english_name: "German",
      iso_639_1: "de",
      name: "Deutsch",
    },
    {
      english_name: "Swedish",
      iso_639_1: "sv",
      name: "svenska",
    },
    {
      english_name: "Italian",
      iso_639_1: "it",
      name: "Italiano",
    },
    {
      english_name: "Russian",
      iso_639_1: "ru",
      name: "Pусский",
    },
  ],
  status: "Released",
  tagline: "Nothing on Earth could come between them.",
  title: "Titanic",
  video: false,
  vote_average: 7.9,
  vote_count: 19931,
};

const credits = {
  id: 597,
  cast: [
    {
      adult: false,
      gender: 2,
      id: 6193,
      known_for_department: "Acting",
      name: "Leonardo DiCaprio",
      original_name: "Leonardo DiCaprio",
      popularity: 23.614,
      profile_path: "/posters/titanic/Leo.jpeg",
      cast_id: 21,
      character: "Jack Dawson",
      credit_id: "52fe425ac3a36847f80179cf",
      order: 0,
    },
    {
      adult: false,
      gender: 1,
      id: 204,
      known_for_department: "Acting",
      name: "Kate Winslet",
      original_name: "Kate Winslet",
      popularity: 14.919,
      profile_path: "/dgIrPQjcdfCnKiGc8ugg5W3GzFX.jpg",
      cast_id: 20,
      character: "Rose DeWitt Bukater",
      credit_id: "52fe425ac3a36847f80179cb",
      order: 1,
    },
    {
      adult: false,
      gender: 2,
      id: 1954,
      known_for_department: "Acting",
      name: "Billy Zane",
      original_name: "Billy Zane",
      popularity: 15.999,
      profile_path: "/9HIubetYWAVLlHNb9aObL0fc0sT.jpg",
      cast_id: 23,
      character: "Cal Hockley",
      credit_id: "52fe425ac3a36847f80179d7",
      order: 2,
    },
    {
      adult: false,
      gender: 1,
      id: 8534,
      known_for_department: "Acting",
      name: "Kathy Bates",
      original_name: "Kathy Bates",
      popularity: 9.516,
      profile_path: "/qZRTzTjV4OC1Ii9a0n8QBS9zMOd.jpg",
      cast_id: 24,
      character: "Molly Brown",
      credit_id: "52fe425ac3a36847f80179db",
      order: 3,
    },
    {
      adult: false,
      gender: 1,
      id: 3713,
      known_for_department: "Acting",
      name: "Frances Fisher",
      original_name: "Frances Fisher",
      popularity: 5.595,
      profile_path: "/tsyGcoXGRNM8KGLpLG3OuxAyxx2.jpg",
      cast_id: 22,
      character: "Ruth Dewitt Bukater",
      credit_id: "52fe425ac3a36847f80179d3",
      order: 4,
    },
  ],
};

export { movie, credits };
